// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package annotators

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "Annotator name, unique within your workspace [required]"},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create annotator",
		Long:    "Create an annotator, a human labeller who can be assigned annotation tasks",
		Example: "  calibrate annotators create --name <value>",
		RunE:    runCreateCmd,
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateAnnotatorEndpointAnnotatorsPostRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateAnnotatorEndpointAnnotatorsPostRequest](cmd, createCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Annotators.Create(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
