// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type BulkCreateItemsAnnotationTasksTaskUUIDItemsPostRequest struct {
	// Annotation task to act on
	TaskUUID string                                    `pathParam:"style=simple,explode=false,name=task_uuid"`
	XAPIKey  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body     components.BulkItemsRequest               `request:"mediaType=application/json"`
}

func (b *BulkCreateItemsAnnotationTasksTaskUUIDItemsPostRequest) GetTaskUUID() string {
	if b == nil {
		return ""
	}
	return b.TaskUUID
}

func (b *BulkCreateItemsAnnotationTasksTaskUUIDItemsPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.XAPIKey
}

func (b *BulkCreateItemsAnnotationTasksTaskUUIDItemsPostRequest) GetBody() components.BulkItemsRequest {
	if b == nil {
		return components.BulkItemsRequest{}
	}
	return b.Body
}

type BulkCreateItemsAnnotationTasksTaskUUIDItemsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	BulkCreateItemsResponse *components.BulkCreateItemsResponse
}

func (b BulkCreateItemsAnnotationTasksTaskUUIDItemsPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkCreateItemsAnnotationTasksTaskUUIDItemsPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkCreateItemsAnnotationTasksTaskUUIDItemsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BulkCreateItemsAnnotationTasksTaskUUIDItemsPostResponse) GetBulkCreateItemsResponse() *components.BulkCreateItemsResponse {
	if b == nil {
		return nil
	}
	return b.BulkCreateItemsResponse
}
