// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutRequest struct {
	// Annotation task to act on
	TaskUUID string                                    `pathParam:"style=simple,explode=false,name=task_uuid"`
	XAPIKey  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body     components.BulkUpdateItemsRequest         `request:"mediaType=application/json"`
}

func (b *BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutRequest) GetTaskUUID() string {
	if b == nil {
		return ""
	}
	return b.TaskUUID
}

func (b *BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.XAPIKey
}

func (b *BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutRequest) GetBody() components.BulkUpdateItemsRequest {
	if b == nil {
		return components.BulkUpdateItemsRequest{}
	}
	return b.Body
}

type BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	BulkUpdateItemsResponse *components.BulkUpdateItemsResponse
}

func (b BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutResponse) GetBulkUpdateItemsResponse() *components.BulkUpdateItemsResponse {
	if b == nil {
		return nil
	}
	return b.BulkUpdateItemsResponse
}
