// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostRequest struct {
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body    components.AgentTestBulkDelete            `request:"mediaType=application/json"`
}

func (b *BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.XAPIKey
}

func (b *BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostRequest) GetBody() components.AgentTestBulkDelete {
	if b == nil {
		return components.AgentTestBulkDelete{}
	}
	return b.Body
}

type BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	AgentTestsBulkUnlinkResponse *components.AgentTestsBulkUnlinkResponse
}

func (b BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostResponse) GetAgentTestsBulkUnlinkResponse() *components.AgentTestsBulkUnlinkResponse {
	if b == nil {
		return nil
	}
	return b.AgentTestsBulkUnlinkResponse
}
