// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type CreateAgentEndpointAgentsPostRequest struct {
	XAPIKey  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	XOrgUUID optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-Org-UUID"`
	Body     components.AgentCreate                    `request:"mediaType=application/json"`
}

func (c *CreateAgentEndpointAgentsPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.XAPIKey
}

func (c *CreateAgentEndpointAgentsPostRequest) GetXOrgUUID() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.XOrgUUID
}

func (c *CreateAgentEndpointAgentsPostRequest) GetBody() components.AgentCreate {
	if c == nil {
		return components.AgentCreate{}
	}
	return c.Body
}

type CreateAgentEndpointAgentsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	AgentCreateResponse *components.AgentCreateResponse
}

func (c CreateAgentEndpointAgentsPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAgentEndpointAgentsPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAgentEndpointAgentsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAgentEndpointAgentsPostResponse) GetAgentCreateResponse() *components.AgentCreateResponse {
	if c == nil {
		return nil
	}
	return c.AgentCreateResponse
}
