// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type CreateTestEndpointTestsPostRequest struct {
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body    components.TestCreate                     `request:"mediaType=application/json"`
}

func (c *CreateTestEndpointTestsPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.XAPIKey
}

func (c *CreateTestEndpointTestsPostRequest) GetBody() components.TestCreate {
	if c == nil {
		return components.TestCreate{}
	}
	return c.Body
}

type CreateTestEndpointTestsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TestCreateResponse *components.TestCreateResponse
}

func (c CreateTestEndpointTestsPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTestEndpointTestsPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTestEndpointTestsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateTestEndpointTestsPostResponse) GetTestCreateResponse() *components.TestCreateResponse {
	if c == nil {
		return nil
	}
	return c.TestCreateResponse
}
