// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type CreateEvaluatorEndpointEvaluatorsPostRequest struct {
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body    components.EvaluatorCreate                `request:"mediaType=application/json"`
}

func (c *CreateEvaluatorEndpointEvaluatorsPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.XAPIKey
}

func (c *CreateEvaluatorEndpointEvaluatorsPostRequest) GetBody() components.EvaluatorCreate {
	if c == nil {
		return components.EvaluatorCreate{}
	}
	return c.Body
}

type CreateEvaluatorEndpointEvaluatorsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EvaluatorCreateResponse *components.EvaluatorCreateResponse
}

func (c CreateEvaluatorEndpointEvaluatorsPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEvaluatorEndpointEvaluatorsPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEvaluatorEndpointEvaluatorsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEvaluatorEndpointEvaluatorsPostResponse) GetEvaluatorCreateResponse() *components.EvaluatorCreateResponse {
	if c == nil {
		return nil
	}
	return c.EvaluatorCreateResponse
}
