// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type CreateAnnotatorEndpointAnnotatorsPostRequest struct {
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body    components.AnnotatorCreate                `request:"mediaType=application/json"`
}

func (c *CreateAnnotatorEndpointAnnotatorsPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.XAPIKey
}

func (c *CreateAnnotatorEndpointAnnotatorsPostRequest) GetBody() components.AnnotatorCreate {
	if c == nil {
		return components.AnnotatorCreate{}
	}
	return c.Body
}

type CreateAnnotatorEndpointAnnotatorsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	AnnotatorCreateResponse *components.AnnotatorCreateResponse
}

func (c CreateAnnotatorEndpointAnnotatorsPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAnnotatorEndpointAnnotatorsPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAnnotatorEndpointAnnotatorsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAnnotatorEndpointAnnotatorsPostResponse) GetAnnotatorCreateResponse() *components.AnnotatorCreateResponse {
	if c == nil {
		return nil
	}
	return c.AnnotatorCreateResponse
}
