// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type CreateVersionEvaluatorsEvaluatorUUIDVersionsPostRequest struct {
	// Evaluator to add a version to
	EvaluatorUUID string                                    `pathParam:"style=simple,explode=false,name=evaluator_uuid"`
	XAPIKey       optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body          components.EvaluatorVersionCreateRequest  `request:"mediaType=application/json"`
}

func (c *CreateVersionEvaluatorsEvaluatorUUIDVersionsPostRequest) GetEvaluatorUUID() string {
	if c == nil {
		return ""
	}
	return c.EvaluatorUUID
}

func (c *CreateVersionEvaluatorsEvaluatorUUIDVersionsPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.XAPIKey
}

func (c *CreateVersionEvaluatorsEvaluatorUUIDVersionsPostRequest) GetBody() components.EvaluatorVersionCreateRequest {
	if c == nil {
		return components.EvaluatorVersionCreateRequest{}
	}
	return c.Body
}

type CreateVersionEvaluatorsEvaluatorUUIDVersionsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	VersionCreateResponse *components.VersionCreateResponse
}

func (c CreateVersionEvaluatorsEvaluatorUUIDVersionsPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateVersionEvaluatorsEvaluatorUUIDVersionsPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateVersionEvaluatorsEvaluatorUUIDVersionsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateVersionEvaluatorsEvaluatorUUIDVersionsPostResponse) GetVersionCreateResponse() *components.VersionCreateResponse {
	if c == nil {
		return nil
	}
	return c.VersionCreateResponse
}
