// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type CreateAnnotationTaskEndpointAnnotationTasksPostRequest struct {
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body    components.AnnotationTaskCreate           `request:"mediaType=application/json"`
}

func (c *CreateAnnotationTaskEndpointAnnotationTasksPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.XAPIKey
}

func (c *CreateAnnotationTaskEndpointAnnotationTasksPostRequest) GetBody() components.AnnotationTaskCreate {
	if c == nil {
		return components.AnnotationTaskCreate{}
	}
	return c.Body
}

type CreateAnnotationTaskEndpointAnnotationTasksPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	AnnotationTaskCreateResponse *components.AnnotationTaskCreateResponse
}

func (c CreateAnnotationTaskEndpointAnnotationTasksPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAnnotationTaskEndpointAnnotationTasksPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAnnotationTaskEndpointAnnotationTasksPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAnnotationTaskEndpointAnnotationTasksPostResponse) GetAnnotationTaskCreateResponse() *components.AnnotationTaskCreateResponse {
	if c == nil {
		return nil
	}
	return c.AnnotationTaskCreateResponse
}
