// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type GetAgentTestRunsAgentTestsAgentAgentUUIDRunsGetRequest struct {
	// Agent whose test runs to list
	AgentUUID string                                    `pathParam:"style=simple,explode=false,name=agent_uuid"`
	XAPIKey   optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
}

func (g *GetAgentTestRunsAgentTestsAgentAgentUUIDRunsGetRequest) GetAgentUUID() string {
	if g == nil {
		return ""
	}
	return g.AgentUUID
}

func (g *GetAgentTestRunsAgentTestsAgentAgentUUIDRunsGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XAPIKey
}

type GetAgentTestRunsAgentTestsAgentAgentUUIDRunsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	AgentTestRunsResponse *components.AgentTestRunsResponse
}

func (g GetAgentTestRunsAgentTestsAgentAgentUUIDRunsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAgentTestRunsAgentTestsAgentAgentUUIDRunsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAgentTestRunsAgentTestsAgentAgentUUIDRunsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAgentTestRunsAgentTestsAgentAgentUUIDRunsGetResponse) GetAgentTestRunsResponse() *components.AgentTestRunsResponse {
	if g == nil {
		return nil
	}
	return g.AgentTestRunsResponse
}
