// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type GetAgentEndpointAgentsAgentUUIDGetRequest struct {
	// The agent to retrieve. Must be in your workspace.
	AgentUUID string                                    `pathParam:"style=simple,explode=false,name=agent_uuid"`
	XAPIKey   optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	XOrgUUID  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-Org-UUID"`
}

func (g *GetAgentEndpointAgentsAgentUUIDGetRequest) GetAgentUUID() string {
	if g == nil {
		return ""
	}
	return g.AgentUUID
}

func (g *GetAgentEndpointAgentsAgentUUIDGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XAPIKey
}

func (g *GetAgentEndpointAgentsAgentUUIDGetRequest) GetXOrgUUID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XOrgUUID
}

type GetAgentEndpointAgentsAgentUUIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	RoutersAgentsAgentResponse *components.RoutersAgentsAgentResponse
}

func (g GetAgentEndpointAgentsAgentUUIDGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAgentEndpointAgentsAgentUUIDGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAgentEndpointAgentsAgentUUIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAgentEndpointAgentsAgentUUIDGetResponse) GetRoutersAgentsAgentResponse() *components.RoutersAgentsAgentResponse {
	if g == nil {
		return nil
	}
	return g.RoutersAgentsAgentResponse
}
