// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest struct {
	// Agent whose linked tests to list
	AgentUUID string `pathParam:"style=simple,explode=false,name=agent_uuid"`
	// Case-insensitive substring search on `name`. Blank is a no-op
	Q optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=q"`
	// Maximum number of items to return. Omit for no limit (all items)
	Limit optionalnullable.OptionalNullable[int64] `queryParam:"style=form,explode=true,name=limit"`
	// Number of items to skip before returning results
	Offset  *int64                                    `default:"0" queryParam:"style=form,explode=true,name=offset"`
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
}

func (g GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest) GetAgentUUID() string {
	if g == nil {
		return ""
	}
	return g.AgentUUID
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest) GetQ() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Q
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest) GetLimit() optionalnullable.OptionalNullable[int64] {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XAPIKey
}

type GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PaginatedResponseTestListResponse *components.PaginatedResponseTestListResponse
}

func (g GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse) GetPaginatedResponseTestListResponse() *components.PaginatedResponseTestListResponse {
	if g == nil {
		return nil
	}
	return g.PaginatedResponseTestListResponse
}
