// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type GetAgentTestRunStatusAgentTestsRunTaskIDGetRequest struct {
	// Test run to poll for status and results
	TaskID   string                                    `pathParam:"style=simple,explode=false,name=task_id"`
	XAPIKey  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	XOrgUUID optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-Org-UUID"`
}

func (g *GetAgentTestRunStatusAgentTestsRunTaskIDGetRequest) GetTaskID() string {
	if g == nil {
		return ""
	}
	return g.TaskID
}

func (g *GetAgentTestRunStatusAgentTestsRunTaskIDGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XAPIKey
}

func (g *GetAgentTestRunStatusAgentTestsRunTaskIDGetRequest) GetXOrgUUID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XOrgUUID
}

type GetAgentTestRunStatusAgentTestsRunTaskIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TestRunStatusResponse *components.TestRunStatusResponse
}

func (g GetAgentTestRunStatusAgentTestsRunTaskIDGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAgentTestRunStatusAgentTestsRunTaskIDGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAgentTestRunStatusAgentTestsRunTaskIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAgentTestRunStatusAgentTestsRunTaskIDGetResponse) GetTestRunStatusResponse() *components.TestRunStatusResponse {
	if g == nil {
		return nil
	}
	return g.TestRunStatusResponse
}
