// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest struct {
	// Agent whose linked tests to list
	AgentUUID string                                    `pathParam:"style=simple,explode=false,name=agent_uuid"`
	XAPIKey   optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest) GetAgentUUID() string {
	if g == nil {
		return ""
	}
	return g.AgentUUID
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XAPIKey
}

type GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseGetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGet []components.RoutersAgentTestsTestResponse
}

func (g GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetResponse) GetResponseGetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGet() []components.RoutersAgentTestsTestResponse {
	if g == nil {
		return nil
	}
	return g.ResponseGetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGet
}
