// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type GetEvaluatorEndpointEvaluatorsEvaluatorUUIDGetRequest struct {
	// Evaluator to retrieve
	EvaluatorUUID string                                    `pathParam:"style=simple,explode=false,name=evaluator_uuid"`
	XAPIKey       optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
}

func (g *GetEvaluatorEndpointEvaluatorsEvaluatorUUIDGetRequest) GetEvaluatorUUID() string {
	if g == nil {
		return ""
	}
	return g.EvaluatorUUID
}

func (g *GetEvaluatorEndpointEvaluatorsEvaluatorUUIDGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XAPIKey
}

type GetEvaluatorEndpointEvaluatorsEvaluatorUUIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EvaluatorDetailResponse *components.EvaluatorDetailResponse
}

func (g GetEvaluatorEndpointEvaluatorsEvaluatorUUIDGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEvaluatorEndpointEvaluatorsEvaluatorUUIDGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetEvaluatorEndpointEvaluatorsEvaluatorUUIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEvaluatorEndpointEvaluatorsEvaluatorUUIDGetResponse) GetEvaluatorDetailResponse() *components.EvaluatorDetailResponse {
	if g == nil {
		return nil
	}
	return g.EvaluatorDetailResponse
}
