// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type GetTestEndpointTestsTestUUIDGetRequest struct {
	// Test to retrieve
	TestUUID string                                    `pathParam:"style=simple,explode=false,name=test_uuid"`
	XAPIKey  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	XOrgUUID optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-Org-UUID"`
}

func (g *GetTestEndpointTestsTestUUIDGetRequest) GetTestUUID() string {
	if g == nil {
		return ""
	}
	return g.TestUUID
}

func (g *GetTestEndpointTestsTestUUIDGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XAPIKey
}

func (g *GetTestEndpointTestsTestUUIDGetRequest) GetXOrgUUID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.XOrgUUID
}

type GetTestEndpointTestsTestUUIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	RoutersTestsTestResponse *components.RoutersTestsTestResponse
}

func (g GetTestEndpointTestsTestUUIDGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTestEndpointTestsTestUUIDGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTestEndpointTestsTestUUIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTestEndpointTestsTestUUIDGetResponse) GetRoutersTestsTestResponse() *components.RoutersTestsTestResponse {
	if g == nil {
		return nil
	}
	return g.RoutersTestsTestResponse
}
