// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostRequest struct {
	// Annotation task to act on
	TaskUUID string                                    `pathParam:"style=simple,explode=false,name=task_uuid"`
	XAPIKey  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body     components.EvaluatorLinkRequest           `request:"mediaType=application/json"`
}

func (l *LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostRequest) GetTaskUUID() string {
	if l == nil {
		return ""
	}
	return l.TaskUUID
}

func (l *LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.XAPIKey
}

func (l *LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostRequest) GetBody() components.EvaluatorLinkRequest {
	if l == nil {
		return components.EvaluatorLinkRequest{}
	}
	return l.Body
}

type LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EvaluatorLinkResponse *components.EvaluatorLinkResponse
}

func (l LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostResponse) GetEvaluatorLinkResponse() *components.EvaluatorLinkResponse {
	if l == nil {
		return nil
	}
	return l.EvaluatorLinkResponse
}
