// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostRequest struct {
	// The agent to link the evaluators to
	AgentUUID string                                    `pathParam:"style=simple,explode=false,name=agent_uuid"`
	XAPIKey   optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body      components.EvaluatorLinkRequest           `request:"mediaType=application/json"`
}

func (l *LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostRequest) GetAgentUUID() string {
	if l == nil {
		return ""
	}
	return l.AgentUUID
}

func (l *LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.XAPIKey
}

func (l *LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostRequest) GetBody() components.EvaluatorLinkRequest {
	if l == nil {
		return components.EvaluatorLinkRequest{}
	}
	return l.Body
}

type LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EvaluatorLinkResponse *components.EvaluatorLinkResponse
}

func (l LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostResponse) GetEvaluatorLinkResponse() *components.EvaluatorLinkResponse {
	if l == nil {
		return nil
	}
	return l.EvaluatorLinkResponse
}
