// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type ListAnnotationTasksAnnotationTasksGetRequest struct {
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
}

func (l *ListAnnotationTasksAnnotationTasksGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.XAPIKey
}

type ListAnnotationTasksAnnotationTasksGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseListAnnotationTasksAnnotationTasksGet []components.AnnotationTaskResponse
}

func (l ListAnnotationTasksAnnotationTasksGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAnnotationTasksAnnotationTasksGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAnnotationTasksAnnotationTasksGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAnnotationTasksAnnotationTasksGetResponse) GetResponseListAnnotationTasksAnnotationTasksGet() []components.AnnotationTaskResponse {
	if l == nil {
		return nil
	}
	return l.ResponseListAnnotationTasksAnnotationTasksGet
}
