// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// EvaluatorType - Filter by what the evaluator judges. Omit for all types
type EvaluatorType string

const (
	EvaluatorTypeTts          EvaluatorType = "tts"
	EvaluatorTypeStt          EvaluatorType = "stt"
	EvaluatorTypeLlm          EvaluatorType = "llm"
	EvaluatorTypeLlmGeneral   EvaluatorType = "llm-general"
	EvaluatorTypeConversation EvaluatorType = "conversation"
)

func (e EvaluatorType) ToPointer() *EvaluatorType {
	return &e
}
func (e *EvaluatorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tts":
		fallthrough
	case "stt":
		fallthrough
	case "llm":
		fallthrough
	case "llm-general":
		fallthrough
	case "conversation":
		*e = EvaluatorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EvaluatorType: %v", v)
	}
}

// DataType - Filter by modality. Omit for all
type DataType string

const (
	DataTypeText  DataType = "text"
	DataTypeAudio DataType = "audio"
)

func (e DataType) ToPointer() *DataType {
	return &e
}
func (e *DataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "audio":
		*e = DataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DataType: %v", v)
	}
}

type ListEvaluatorsEvaluatorsGetRequest struct {
	// Filter by what the evaluator judges. Omit for all types
	EvaluatorType optionalnullable.OptionalNullable[EvaluatorType] `queryParam:"style=form,explode=true,name=evaluator_type"`
	// Filter by modality. Omit for all
	DataType optionalnullable.OptionalNullable[DataType] `queryParam:"style=form,explode=true,name=data_type"`
	// When `true`, include the built-in default evaluators alongside the ones you created
	IncludeDefaults *bool                                     `default:"true" queryParam:"style=form,explode=true,name=include_defaults"`
	XAPIKey         optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
}

func (l ListEvaluatorsEvaluatorsGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEvaluatorsEvaluatorsGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListEvaluatorsEvaluatorsGetRequest) GetEvaluatorType() optionalnullable.OptionalNullable[EvaluatorType] {
	if l == nil {
		return nil
	}
	return l.EvaluatorType
}

func (l *ListEvaluatorsEvaluatorsGetRequest) GetDataType() optionalnullable.OptionalNullable[DataType] {
	if l == nil {
		return nil
	}
	return l.DataType
}

func (l *ListEvaluatorsEvaluatorsGetRequest) GetIncludeDefaults() *bool {
	if l == nil {
		return nil
	}
	return l.IncludeDefaults
}

func (l *ListEvaluatorsEvaluatorsGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.XAPIKey
}

type ListEvaluatorsEvaluatorsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseListEvaluatorsEvaluatorsGet []components.RoutersEvaluatorsEvaluatorResponse
}

func (l ListEvaluatorsEvaluatorsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEvaluatorsEvaluatorsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListEvaluatorsEvaluatorsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListEvaluatorsEvaluatorsGetResponse) GetResponseListEvaluatorsEvaluatorsGet() []components.RoutersEvaluatorsEvaluatorResponse {
	if l == nil {
		return nil
	}
	return l.ResponseListEvaluatorsEvaluatorsGet
}
