// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type ListAnnotatorsAnnotatorsGetRequest struct {
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
}

func (l *ListAnnotatorsAnnotatorsGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.XAPIKey
}

type ListAnnotatorsAnnotatorsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseListAnnotatorsAnnotatorsGet []components.AnnotatorResponse
}

func (l ListAnnotatorsAnnotatorsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAnnotatorsAnnotatorsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAnnotatorsAnnotatorsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAnnotatorsAnnotatorsGetResponse) GetResponseListAnnotatorsAnnotatorsGet() []components.AnnotatorResponse {
	if l == nil {
		return nil
	}
	return l.ResponseListAnnotatorsAnnotatorsGet
}
