// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type ListAgentsAgentsGetRequest struct {
	XAPIKey  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	XOrgUUID optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-Org-UUID"`
}

func (l *ListAgentsAgentsGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.XAPIKey
}

func (l *ListAgentsAgentsGetRequest) GetXOrgUUID() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.XOrgUUID
}

type ListAgentsAgentsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseListAgentsAgentsGet []components.RoutersAgentToolsAgentResponse
}

func (l ListAgentsAgentsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentsAgentsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentsAgentsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAgentsAgentsGetResponse) GetResponseListAgentsAgentsGet() []components.RoutersAgentToolsAgentResponse {
	if l == nil {
		return nil
	}
	return l.ResponseListAgentsAgentsGet
}
