// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type ListAnnotationTasksAnnotationTasksGetRequest struct {
	// Case-insensitive substring search on `name`. Blank is a no-op
	Q optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=q"`
	// Maximum number of items to return. Omit for no limit (all items)
	Limit optionalnullable.OptionalNullable[int64] `queryParam:"style=form,explode=true,name=limit"`
	// Number of items to skip before returning results
	Offset  *int64                                    `default:"0" queryParam:"style=form,explode=true,name=offset"`
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
}

func (l ListAnnotationTasksAnnotationTasksGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAnnotationTasksAnnotationTasksGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAnnotationTasksAnnotationTasksGetRequest) GetQ() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.Q
}

func (l *ListAnnotationTasksAnnotationTasksGetRequest) GetLimit() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListAnnotationTasksAnnotationTasksGetRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListAnnotationTasksAnnotationTasksGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.XAPIKey
}

type ListAnnotationTasksAnnotationTasksGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PaginatedResponseAnnotationTaskResponse *components.PaginatedResponseAnnotationTaskResponse
}

func (l ListAnnotationTasksAnnotationTasksGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAnnotationTasksAnnotationTasksGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAnnotationTasksAnnotationTasksGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAnnotationTasksAnnotationTasksGetResponse) GetPaginatedResponseAnnotationTaskResponse() *components.PaginatedResponseAnnotationTaskResponse {
	if l == nil {
		return nil
	}
	return l.PaginatedResponseAnnotationTaskResponse
}
