// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type ResolveAgentNamesAgentsResolvePostRequest struct {
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body    components.ResolveAgentNamesRequest       `request:"mediaType=application/json"`
}

func (r *ResolveAgentNamesAgentsResolvePostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.XAPIKey
}

func (r *ResolveAgentNamesAgentsResolvePostRequest) GetBody() components.ResolveAgentNamesRequest {
	if r == nil {
		return components.ResolveAgentNamesRequest{}
	}
	return r.Body
}

type ResolveAgentNamesAgentsResolvePostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResolveAgentNamesResponse *components.ResolveAgentNamesResponse
}

func (r ResolveAgentNamesAgentsResolvePostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResolveAgentNamesAgentsResolvePostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ResolveAgentNamesAgentsResolvePostResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ResolveAgentNamesAgentsResolvePostResponse) GetResolveAgentNamesResponse() *components.ResolveAgentNamesResponse {
	if r == nil {
		return nil
	}
	return r.ResolveAgentNamesResponse
}
