// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type RunTestsBatchAgentTestsRunPostRequest struct {
	XAPIKey  optionalnullable.OptionalNullable[string]                     `header:"style=simple,explode=false,name=X-API-Key"`
	XOrgUUID optionalnullable.OptionalNullable[string]                     `header:"style=simple,explode=false,name=X-Org-UUID"`
	Body     optionalnullable.OptionalNullable[components.BatchRunRequest] `request:"mediaType=application/json"`
}

func (r RunTestsBatchAgentTestsRunPostRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RunTestsBatchAgentTestsRunPostRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RunTestsBatchAgentTestsRunPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.XAPIKey
}

func (r *RunTestsBatchAgentTestsRunPostRequest) GetXOrgUUID() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.XOrgUUID
}

func (r *RunTestsBatchAgentTestsRunPostRequest) GetBody() optionalnullable.OptionalNullable[components.BatchRunRequest] {
	if r == nil {
		return nil
	}
	return r.Body
}

type RunTestsBatchAgentTestsRunPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	BatchTestRunResponse *components.BatchTestRunResponse
}

func (r RunTestsBatchAgentTestsRunPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RunTestsBatchAgentTestsRunPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RunTestsBatchAgentTestsRunPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RunTestsBatchAgentTestsRunPostResponse) GetBatchTestRunResponse() *components.BatchTestRunResponse {
	if r == nil {
		return nil
	}
	return r.BatchTestRunResponse
}
