// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostRequest struct {
	// Annotation task to act on
	TaskUUID string                                    `pathParam:"style=simple,explode=false,name=task_uuid"`
	XAPIKey  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body     components.EvaluatorRunStartRequest       `request:"mediaType=application/json"`
}

func (s *StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostRequest) GetTaskUUID() string {
	if s == nil {
		return ""
	}
	return s.TaskUUID
}

func (s *StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.XAPIKey
}

func (s *StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostRequest) GetBody() components.EvaluatorRunStartRequest {
	if s == nil {
		return components.EvaluatorRunStartRequest{}
	}
	return s.Body
}

type StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EvaluatorRunLaunchResponse *components.EvaluatorRunLaunchResponse
}

func (s StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostResponse) GetEvaluatorRunLaunchResponse() *components.EvaluatorRunLaunchResponse {
	if s == nil {
		return nil
	}
	return s.EvaluatorRunLaunchResponse
}
