// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// Bucket - How to bucket points in the trend series
type Bucket string

const (
	BucketWeek  Bucket = "week"
	BucketMonth Bucket = "month"
	BucketYear  Bucket = "year"
)

func (e Bucket) ToPointer() *Bucket {
	return &e
}
func (e *Bucket) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "week":
		fallthrough
	case "month":
		fallthrough
	case "year":
		*e = Bucket(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Bucket: %v", v)
	}
}

type TaskAgreementAnnotationTasksTaskUUIDAgreementGetRequest struct {
	// Annotation task to act on
	TaskUUID string `pathParam:"style=simple,explode=false,name=task_uuid"`
	// How to bucket points in the trend series
	Bucket *Bucket `default:"week" queryParam:"style=form,explode=true,name=bucket"`
	// Trailing window in days for the trend series
	Days    *int64                                    `default:"90" queryParam:"style=form,explode=true,name=days"`
	XAPIKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
}

func (t TaskAgreementAnnotationTasksTaskUUIDAgreementGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskAgreementAnnotationTasksTaskUUIDAgreementGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskAgreementAnnotationTasksTaskUUIDAgreementGetRequest) GetTaskUUID() string {
	if t == nil {
		return ""
	}
	return t.TaskUUID
}

func (t *TaskAgreementAnnotationTasksTaskUUIDAgreementGetRequest) GetBucket() *Bucket {
	if t == nil {
		return nil
	}
	return t.Bucket
}

func (t *TaskAgreementAnnotationTasksTaskUUIDAgreementGetRequest) GetDays() *int64 {
	if t == nil {
		return nil
	}
	return t.Days
}

func (t *TaskAgreementAnnotationTasksTaskUUIDAgreementGetRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.XAPIKey
}

type TaskAgreementAnnotationTasksTaskUUIDAgreementGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TaskAgreementResponse *components.TaskAgreementResponse
}

func (t TaskAgreementAnnotationTasksTaskUUIDAgreementGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskAgreementAnnotationTasksTaskUUIDAgreementGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskAgreementAnnotationTasksTaskUUIDAgreementGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TaskAgreementAnnotationTasksTaskUUIDAgreementGetResponse) GetTaskAgreementResponse() *components.TaskAgreementResponse {
	if t == nil {
		return nil
	}
	return t.TaskAgreementResponse
}
