// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type UpdateTestEndpointTestsTestUUIDPutRequest struct {
	// Test to update
	TestUUID string                                    `pathParam:"style=simple,explode=false,name=test_uuid"`
	XAPIKey  optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body     components.TestUpdate                     `request:"mediaType=application/json"`
}

func (u *UpdateTestEndpointTestsTestUUIDPutRequest) GetTestUUID() string {
	if u == nil {
		return ""
	}
	return u.TestUUID
}

func (u *UpdateTestEndpointTestsTestUUIDPutRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.XAPIKey
}

func (u *UpdateTestEndpointTestsTestUUIDPutRequest) GetBody() components.TestUpdate {
	if u == nil {
		return components.TestUpdate{}
	}
	return u.Body
}

type UpdateTestEndpointTestsTestUUIDPutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TestResponse *components.TestResponse
}

func (u UpdateTestEndpointTestsTestUUIDPutResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTestEndpointTestsTestUUIDPutResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTestEndpointTestsTestUUIDPutResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateTestEndpointTestsTestUUIDPutResponse) GetTestResponse() *components.TestResponse {
	if u == nil {
		return nil
	}
	return u.TestResponse
}
