// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type UpdateAnnotatorEndpointAnnotatorsAnnotatorUUIDPutRequest struct {
	// Annotator to update
	AnnotatorUUID string                                    `pathParam:"style=simple,explode=false,name=annotator_uuid"`
	XAPIKey       optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body          components.AnnotatorUpdate                `request:"mediaType=application/json"`
}

func (u *UpdateAnnotatorEndpointAnnotatorsAnnotatorUUIDPutRequest) GetAnnotatorUUID() string {
	if u == nil {
		return ""
	}
	return u.AnnotatorUUID
}

func (u *UpdateAnnotatorEndpointAnnotatorsAnnotatorUUIDPutRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.XAPIKey
}

func (u *UpdateAnnotatorEndpointAnnotatorsAnnotatorUUIDPutRequest) GetBody() components.AnnotatorUpdate {
	if u == nil {
		return components.AnnotatorUpdate{}
	}
	return u.Body
}

type UpdateAnnotatorEndpointAnnotatorsAnnotatorUUIDPutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	AnnotatorResponse *components.AnnotatorResponse
}

func (u UpdateAnnotatorEndpointAnnotatorsAnnotatorUUIDPutResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAnnotatorEndpointAnnotatorsAnnotatorUUIDPutResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAnnotatorEndpointAnnotatorsAnnotatorUUIDPutResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAnnotatorEndpointAnnotatorsAnnotatorUUIDPutResponse) GetAnnotatorResponse() *components.AnnotatorResponse {
	if u == nil {
		return nil
	}
	return u.AnnotatorResponse
}
