// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type UpdateAgentEndpointAgentsAgentUUIDPutRequest struct {
	// The agent to update
	AgentUUID string                                    `pathParam:"style=simple,explode=false,name=agent_uuid"`
	XAPIKey   optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body      components.AgentUpdate                    `request:"mediaType=application/json"`
}

func (u *UpdateAgentEndpointAgentsAgentUUIDPutRequest) GetAgentUUID() string {
	if u == nil {
		return ""
	}
	return u.AgentUUID
}

func (u *UpdateAgentEndpointAgentsAgentUUIDPutRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.XAPIKey
}

func (u *UpdateAgentEndpointAgentsAgentUUIDPutRequest) GetBody() components.AgentUpdate {
	if u == nil {
		return components.AgentUpdate{}
	}
	return u.Body
}

type UpdateAgentEndpointAgentsAgentUUIDPutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	RoutersAgentsAgentResponse *components.RoutersAgentsAgentResponse
}

func (u UpdateAgentEndpointAgentsAgentUUIDPutResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAgentEndpointAgentsAgentUUIDPutResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAgentEndpointAgentsAgentUUIDPutResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAgentEndpointAgentsAgentUUIDPutResponse) GetRoutersAgentsAgentResponse() *components.RoutersAgentsAgentResponse {
	if u == nil {
		return nil
	}
	return u.RoutersAgentsAgentResponse
}
