// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/models/components"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostRequest struct {
	// The agent whose connection to verify
	AgentUUID string                                    `pathParam:"style=simple,explode=false,name=agent_uuid"`
	XAPIKey   optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=X-API-Key"`
	Body      components.AgentVerifyRequest             `request:"mediaType=application/json"`
}

func (v *VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostRequest) GetAgentUUID() string {
	if v == nil {
		return ""
	}
	return v.AgentUUID
}

func (v *VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostRequest) GetXAPIKey() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.XAPIKey
}

func (v *VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostRequest) GetBody() components.AgentVerifyRequest {
	if v == nil {
		return components.AgentVerifyRequest{}
	}
	return v.Body
}

type VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	VerifyConnectionResponse *components.VerifyConnectionResponse
}

func (v VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostResponse) GetVerifyConnectionResponse() *components.VerifyConnectionResponse {
	if v == nil {
		return nil
	}
	return v.VerifyConnectionResponse
}
