// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package evaluators

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "Evaluator name, unique within your workspace [required]"},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"description,omitempty"`, Description: "Description. Omit to leave blank"},
	{FlagName: "evaluator-type", Shorthand: "e", FieldPath: "Body.EvaluatorType", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "llm", EnumValues: []string{"tts", "stt", "llm", "llm-general", "conversation"}, Description: "What the evaluator judges:\n\n- `tts`: TTS audio\n- `stt`: one transcript\n- `llm`: a reply with its conversation history\n- `llm-general`: a standalone input and output pair\n- `conversation`: a full conversation\n (options: tts, stt, llm, llm-general, conversation)"},
	{FlagName: "data-type", FieldPath: "Body.DataType", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "text", EnumValues: []string{"text", "audio"}, Description: "The modality the judge reads:\n\n- `text`\n- `audio`\n (options: text, audio)"},
	{FlagName: "output-type", FieldPath: "Body.OutputType", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "binary", EnumValues: []string{"binary", "rating"}, Description: "How the evaluator scores:\n\n- `binary`: pass or fail\n- `rating`: a numeric score, using the scale in `output_config`\n (options: binary, rating)"},
	{FlagName: "version-param", Shorthand: "v", FieldPath: "Body.Version", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"version"`, Description: "One version of an evaluator: its judge prompt, model, variables, and rubric. [required]"},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create evaluator",
		Long:    "Create an evaluator along with its first version, which is set live",
		Example: "  calibrate evaluators create --name <value> --version-param '{\"judge_model\":\"<value>\",\"system_prompt\":\"<value>\"}'",
		RunE:    runCreateCmd,
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateEvaluatorEndpointEvaluatorsPostRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateEvaluatorEndpointEvaluatorsPostRequest](cmd, createCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Evaluators.Create(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
