// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package evaluators

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createVersionCmdMeta = []flagutil.FlagMeta{
	{FlagName: "evaluator-uuid", Shorthand: "e", FieldPath: "EvaluatorUUID", Kind: flagutil.FlagKindString, Required: true, Description: "Evaluator to add a version to [required]"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "judge-model", Shorthand: "j", FieldPath: "Body.JudgeModel", Kind: flagutil.FlagKindString, Required: true, Description: "The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4` [required]"},
	{FlagName: "system-prompt", Shorthand: "s", FieldPath: "Body.SystemPrompt", Kind: flagutil.FlagKindString, Required: true, Description: "Judge system prompt. May contain `{ {variable} }` placeholders [required]"},
	{FlagName: "output-config", FieldPath: "Body.OutputConfig", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"output_config,omitempty"`, Description: "The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own"},
	{FlagName: "variables", Shorthand: "v", FieldPath: "Body.Variables", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"variables,omitempty"`, Description: "Declared prompt variables. Omit if the prompt has none. After the first version the variable names are fixed. You can change a variable's description or default, but not add, remove, or rename one"},
	{FlagName: "make-live", Shorthand: "m", FieldPath: "Body.MakeLive", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "When `true`, immediately point the evaluator's live version at this new version"},
}

// initCreateVersionCmd initializes the create-version command.
func initCreateVersionCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-version",
		Short:   "Create evaluator version",
		Long:    "Add a new version to an evaluator you created",
		Example: "  calibrate evaluators create-version --evaluator-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479 --judge-model <value> --system-prompt <value>",
		RunE:    runCreateVersionCmd,
		Aliases: []string{"cv"},
	}
	flagutil.RegisterFlags(cmd, createVersionCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateVersionEvaluatorsEvaluatorUUIDVersionsPostRequest](createVersionCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-version: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateVersionCmd executes the create-version command.
func runCreateVersionCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createVersionCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createVersionCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateVersionEvaluatorsEvaluatorUUIDVersionsPostRequest](cmd, createVersionCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Evaluators.CreateVersion(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
