// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agenttests

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var getRunCaseCmdMeta = []flagutil.FlagMeta{
	{FlagName: "task-id", FieldPath: "TaskID", Kind: flagutil.FlagKindString, Required: true, Description: "Test run or benchmark the case was run in [required]"},
	{FlagName: "test-uuid", FieldPath: "TestUUID", Kind: flagutil.FlagKindString, Required: true, Description: "The test whose result to read, as `test_uuid` on the case [required]"},
	{FlagName: "model", Shorthand: "m", FieldPath: "Model", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=model"`, Description: "Which model's answer to read. Required for a benchmark, which runs every test once per model"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
}

// initGetRunCaseCmd initializes the get-run-case command.
func initGetRunCaseCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-run-case",
		Short:   "Get test case result",
		Long:    "Get the full result of one test case in a run",
		Example: "  calibrate agent-tests get-run-case --task-id a3b2c1d0-e5f4-3210-abcd-ef1234567890 --test-uuid b1c2d3e4-f5a6-7890-bcde-f12345678901",
		RunE:    runGetRunCaseCmd,
		Aliases: []string{"grc"},
	}
	flagutil.RegisterFlags(cmd, getRunCaseCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetAgentTestCaseResultAgentTestsRunTaskIDResultsTestUUIDGetRequest](getRunCaseCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-run-case: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetRunCaseCmd executes the get-run-case command.
func runGetRunCaseCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getRunCaseCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getRunCaseCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetAgentTestCaseResultAgentTestsRunTaskIDResultsTestUUIDGetRequest](cmd, getRunCaseCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AgentTests.GetRunCase(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
