// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agenttests

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var linkCmdMeta = []flagutil.FlagMeta{
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "agent-uuid", Shorthand: "a", FieldPath: "Body.AgentUUID", Kind: flagutil.FlagKindString, Required: true, Description: "Agent to link tests to [required]"},
	{FlagName: "test-uuids", Shorthand: "t", FieldPath: "Body.TestUuids", Kind: flagutil.FlagKindStringArray, Required: true, Description: "Tests to link. Any that are already linked are skipped [required]"},
}

// initLinkCmd initializes the link command.
func initLinkCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "link",
		Short:   "Link tests to agent",
		Long:    "Link one or more tests to an agent. Tests that are already linked are skipped.",
		Example: "  calibrate agent-tests link --agent-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479 --test-uuids '[\"b1c2d3e4-f5a6-7890-bcde-f12345678901\"]'",
		RunE:    runLinkCmd,
	}
	flagutil.RegisterFlags(cmd, linkCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateAgentTestLinksAgentTestsPostRequest](linkCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for link: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runLinkCmd executes the link command.
func runLinkCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, linkCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, linkCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateAgentTestLinksAgentTestsPostRequest](cmd, linkCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AgentTests.Link(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
