// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agenttests

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listForAgentCmdMeta = []flagutil.FlagMeta{
	{FlagName: "agent-uuid", Shorthand: "a", FieldPath: "AgentUUID", Kind: flagutil.FlagKindString, Required: true, Description: "Agent whose linked tests to list [required]"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
}

// initListForAgentCmd initializes the list-for-agent command.
func initListForAgentCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-for-agent",
		Short:   "List tests for agent",
		Long:    "List the tests linked to an agent.",
		Example: "  calibrate agent-tests list-for-agent --agent-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479",
		RunE:    runListForAgentCmd,
		Aliases: []string{"lfa"},
	}
	flagutil.RegisterFlags(cmd, listForAgentCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest](listForAgentCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-for-agent: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListForAgentCmd executes the list-for-agent command.
func runListForAgentCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listForAgentCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listForAgentCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetAgentTestsEndpointAgentTestsAgentAgentUUIDTestsGetRequest](cmd, listForAgentCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AgentTests.ListForAgent(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
