// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var bulkCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "x-api-key", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "x-org-uuid", FieldPath: "XOrgUUID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-Org-UUID"`, Description: "string value"},
	{FlagName: "type", FieldPath: "Body.Type", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"response", "tool_call", "conversation"}, Description: "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation\n\nApplied to every test in the batch. (options: response, tool_call, conversation) [required]"},
	{FlagName: "tests", FieldPath: "Body.Tests", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"tests"`, Description: "Test items to create (non-empty, max 500 per request, names unique within the batch) [required]"},
	{FlagName: "agent-uuids", Shorthand: "a", FieldPath: "Body.AgentUuids", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"agent_uuids,omitempty"`, Description: "Agents (IDs) to link every created test to. Omit to link none"},
	{FlagName: "language", Shorthand: "l", FieldPath: "Body.Language", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"language,omitempty"`, Description: "Language written to each test's `config.settings.language`. Omit to leave unset"},
}

// initBulkCreateCmd initializes the bulk-create command.
func initBulkCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "bulk-create",
		Short:   "Bulk create tests",
		Long:    "Create many test cases at once and link them to your agents",
		Example: "  calibrate tests bulk-create --type tool_call --tests '[{\"name\":\"<value>\",\"conversation_history\":[{\"role\":\"tool\"}],\"evaluators\":[{\"evaluator_uuid\":\"f47ac10b-58cc-4372-a567-0e02b2c3d479\"}]}]'",
		RunE:    runBulkCreateCmd,
		Aliases: []string{"bc"},
	}
	flagutil.RegisterFlags(cmd, bulkCreateCmdMeta)
	if err := flagutil.ValidateMeta[operations.BulkUploadTestsTestsBulkPostRequest](bulkCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for bulk-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runBulkCreateCmd executes the bulk-create command.
func runBulkCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, bulkCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, bulkCreateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.BulkUploadTestsTestsBulkPostRequest](cmd, bulkCreateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Tests.BulkCreate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
