// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitTestsRoot(parent *cobra.Command) error {
	var TestsCmd = &cobra.Command{
		Use:   "tests",
		Short: "Operations for tests",
		Long:  "Operations for tests",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initBulkCreateCmd(TestsCmd); err != nil {
		return err
	}

	if err := initCreateCmd(TestsCmd); err != nil {
		return err
	}

	if err := initListCmd(TestsCmd); err != nil {
		return err
	}

	if err := initGetCmd(TestsCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(TestsCmd); err != nil {
		return err
	}

	parent.AddCommand(TestsCmd)
	return nil
}
