// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentTestRunCreateResponseStatus - Current status of the run
type AgentTestRunCreateResponseStatus string

const (
	AgentTestRunCreateResponseStatusQueued     AgentTestRunCreateResponseStatus = "queued"
	AgentTestRunCreateResponseStatusInProgress AgentTestRunCreateResponseStatus = "in_progress"
)

func (e AgentTestRunCreateResponseStatus) ToPointer() *AgentTestRunCreateResponseStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentTestRunCreateResponseStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "queued", "in_progress":
			return true
		}
	}
	return false
}

type AgentTestRunCreateResponse struct {
	// Test run job ID. Poll it for status and results
	TaskID string `json:"task_id"`
	// Current status of the run
	Status AgentTestRunCreateResponseStatus `json:"status"`
}

func (a *AgentTestRunCreateResponse) GetTaskID() string {
	if a == nil {
		return ""
	}
	return a.TaskID
}

func (a *AgentTestRunCreateResponse) GetStatus() AgentTestRunCreateResponseStatus {
	if a == nil {
		return AgentTestRunCreateResponseStatus("")
	}
	return a.Status
}
