// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentTestRunsResponse struct {
	// Test runs for the agent, most recently created first
	Runs []AgentTestRunListItem `json:"runs"`
}

func (a *AgentTestRunsResponse) GetRuns() []AgentTestRunListItem {
	if a == nil {
		return []AgentTestRunListItem{}
	}
	return a.Runs
}
