// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// AgentTestRunListItemType - What kind of run this is:
// - `llm-unit-test`: a single run of the agent's tests
// - `llm-benchmark`: a multi-model comparison
type AgentTestRunListItemType string

const (
	AgentTestRunListItemTypeLlmUnitTest  AgentTestRunListItemType = "llm-unit-test"
	AgentTestRunListItemTypeLlmBenchmark AgentTestRunListItemType = "llm-benchmark"
)

func (e AgentTestRunListItemType) ToPointer() *AgentTestRunListItemType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentTestRunListItemType) IsExact() bool {
	if e != nil {
		switch *e {
		case "llm-unit-test", "llm-benchmark":
			return true
		}
	}
	return false
}

type AgentTestRunListItem struct {
	// Test run job ID
	UUID string `json:"uuid"`
	// Display name, such as `Run 1` for a unit test or `Benchmark 1` for a benchmark
	Name   string     `json:"name"`
	Status TaskStatus `json:"status"`
	// What kind of run this is:
	// - `llm-unit-test`: a single run of the agent's tests
	// - `llm-benchmark`: a multi-model comparison
	Type AgentTestRunListItemType `json:"type"`
	// When the run was last updated (ISO 8601 UTC)
	UpdatedAt string `json:"updated_at"`
	// Total number of test cases
	TotalTests optionalnullable.OptionalNullable[int64] `json:"total_tests,omitzero"`
	// Number of test cases that passed
	Passed optionalnullable.OptionalNullable[int64] `json:"passed,omitzero"`
	// Number of test cases that failed
	Failed optionalnullable.OptionalNullable[int64] `json:"failed,omitzero"`
	// Flat pass/fail summary for each test case (fetch the run detail for full results)
	Results optionalnullable.OptionalNullable[[]TestRunCaseSummary] `json:"results,omitzero"`
	// Aggregated latency in milliseconds, as `{p50, p95, p99, count}`
	LatencyMs optionalnullable.OptionalNullable[map[string]any] `json:"latency_ms,omitzero"`
	// Aggregated cost as `{mean, min, max, count}` (USD)
	Cost optionalnullable.OptionalNullable[map[string]any] `json:"cost,omitzero"`
	// Aggregated token usage as `{mean, min, max, count}`
	TotalTokens optionalnullable.OptionalNullable[map[string]any] `json:"total_tokens,omitzero"`
	// Flat summary for each model in a benchmark run (fetch the benchmark detail for full results)
	ModelResults optionalnullable.OptionalNullable[[]ModelRunSummary] `json:"model_results,omitzero"`
	// True if the run failed
	Error *bool `default:"false" json:"error"`
	// Whether the run is shared publicly
	IsPublic *bool `default:"false" json:"is_public"`
	// Token for building the public share URL
	ShareToken optionalnullable.OptionalNullable[string] `json:"share_token,omitzero"`
}

func (a AgentTestRunListItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentTestRunListItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentTestRunListItem) GetUUID() string {
	if a == nil {
		return ""
	}
	return a.UUID
}

func (a *AgentTestRunListItem) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AgentTestRunListItem) GetStatus() TaskStatus {
	if a == nil {
		return TaskStatus("")
	}
	return a.Status
}

func (a *AgentTestRunListItem) GetType() AgentTestRunListItemType {
	if a == nil {
		return AgentTestRunListItemType("")
	}
	return a.Type
}

func (a *AgentTestRunListItem) GetUpdatedAt() string {
	if a == nil {
		return ""
	}
	return a.UpdatedAt
}

func (a *AgentTestRunListItem) GetTotalTests() optionalnullable.OptionalNullable[int64] {
	if a == nil {
		return nil
	}
	return a.TotalTests
}

func (a *AgentTestRunListItem) GetPassed() optionalnullable.OptionalNullable[int64] {
	if a == nil {
		return nil
	}
	return a.Passed
}

func (a *AgentTestRunListItem) GetFailed() optionalnullable.OptionalNullable[int64] {
	if a == nil {
		return nil
	}
	return a.Failed
}

func (a *AgentTestRunListItem) GetResults() optionalnullable.OptionalNullable[[]TestRunCaseSummary] {
	if a == nil {
		return nil
	}
	return a.Results
}

func (a *AgentTestRunListItem) GetLatencyMs() optionalnullable.OptionalNullable[map[string]any] {
	if a == nil {
		return nil
	}
	return a.LatencyMs
}

func (a *AgentTestRunListItem) GetCost() optionalnullable.OptionalNullable[map[string]any] {
	if a == nil {
		return nil
	}
	return a.Cost
}

func (a *AgentTestRunListItem) GetTotalTokens() optionalnullable.OptionalNullable[map[string]any] {
	if a == nil {
		return nil
	}
	return a.TotalTokens
}

func (a *AgentTestRunListItem) GetModelResults() optionalnullable.OptionalNullable[[]ModelRunSummary] {
	if a == nil {
		return nil
	}
	return a.ModelResults
}

func (a *AgentTestRunListItem) GetError() *bool {
	if a == nil {
		return nil
	}
	return a.Error
}

func (a *AgentTestRunListItem) GetIsPublic() *bool {
	if a == nil {
		return nil
	}
	return a.IsPublic
}

func (a *AgentTestRunListItem) GetShareToken() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.ShareToken
}
