// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// AgentCreateType - - `agent`: built inside Calibrate
// - `connection`: your existing agent connected to Calibrate
type AgentCreateType string

const (
	AgentCreateTypeAgent      AgentCreateType = "agent"
	AgentCreateTypeConnection AgentCreateType = "connection"
)

func (e AgentCreateType) ToPointer() *AgentCreateType {
	return &e
}
func (e *AgentCreateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agent":
		fallthrough
	case "connection":
		*e = AgentCreateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentCreateType: %v", v)
	}
}

type AgentCreate struct {
	// Agent name, unique within the workspace
	Name string `json:"name"`
	// - `agent`: built inside Calibrate
	// - `connection`: your existing agent connected to Calibrate
	Type *AgentCreateType `default:"agent" json:"type"`
	// Agent behavioral config. The keys depend on `type`.
	//
	// **`type=agent`** (built inside Calibrate):
	// - `system_prompt` (string): the agent's instructions
	// - `llm.model` (string): `provider/model`, e.g. `openai/gpt-4.1` or `google/gemini-2.5-flash`
	// - `stt.provider` (string): `deepgram`, `openai`, `cartesia`, `elevenlabs`, `google`, `sarvam`, or `smallest`
	// - `tts.provider` (string): `cartesia`, `openai`, `google`, `elevenlabs`, `sarvam`, or `smallest`
	// - `settings.agent_speaks_first` (bool), `settings.max_assistant_turns` (int)
	// - `system_tools.end_call` (bool, optional): let the agent end the call
	// - `data_extraction_fields` (array, optional): `[{name, type, description, required}]`
	//
	// ```json
	// {
	//   "system_prompt": "You are a helpful support agent.",
	//   "llm": {"model": "openai/gpt-4.1"},
	//   "stt": {"provider": "deepgram"},
	//   "tts": {"provider": "elevenlabs"},
	//   "settings": {"agent_speaks_first": true, "max_assistant_turns": 50}
	// }
	// ```
	//
	// **`type=connection`** (your own HTTP endpoint):
	// - `agent_url` (string, required): public HTTPS endpoint the agent is called at
	// - `agent_headers` (object, optional): headers sent on each request, e.g. auth
	// - `benchmark_provider` (string, optional): `openrouter` (default), `openai`, `google`, `anthropic`, `meta-llama`, `mistralai`, `deepseek`, `x-ai`, `cohere`, `qwen`, or `ai21`
	//
	// ```json
	// {
	//   "agent_url": "https://api.example.com/agent",
	//   "agent_headers": {"Authorization": "Bearer <token>"},
	//   "benchmark_provider": "openrouter"
	// }
	// ```
	//
	// For `type=agent`, omitted keys inherit managed defaults (omit `config` entirely to use all defaults). For `type=connection`, `config` is stored as-is and must contain `agent_url`.
	Config optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
}

func (a AgentCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentCreate) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AgentCreate) GetType() *AgentCreateType {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AgentCreate) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if a == nil {
		return nil
	}
	return a.Config
}
