// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentTestBulkDelete struct {
	// Agent to unlink tests from
	AgentUUID string `json:"agent_uuid"`
	// Tests to unlink from the agent
	TestUuids []string `json:"test_uuids"`
}

func (a *AgentTestBulkDelete) GetAgentUUID() string {
	if a == nil {
		return ""
	}
	return a.AgentUUID
}

func (a *AgentTestBulkDelete) GetTestUuids() []string {
	if a == nil {
		return []string{}
	}
	return a.TestUuids
}
