// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type AgentUpdate struct {
	// New agent name. Omit to leave the name unchanged
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// Agent behavioral config. The keys depend on `type`.
	//
	// **`type=agent`**, built inside Calibrate:
	// - `system_prompt`: the agent's instructions
	// - `llm.model`: `provider/model`, e.g. `openai/gpt-4.1` or `google/gemini-2.5-flash`
	// - `stt.provider`: `deepgram`, `openai`, `cartesia`, `elevenlabs`, `google`, `sarvam`, or `smallest`
	// - `tts.provider`: `cartesia`, `openai`, `google`, `elevenlabs`, `sarvam`, or `smallest`
	// - `settings.agent_speaks_first`, `settings.max_assistant_turns`
	// - `system_tools.end_call`: let the agent end the call
	// - `data_extraction_fields`: `[{name, type, description, required}]`
	//
	// ```json
	// {
	//   "system_prompt": "You are a helpful support agent.",
	//   "llm": {"model": "openai/gpt-4.1"},
	//   "stt": {"provider": "deepgram"},
	//   "tts": {"provider": "elevenlabs"},
	//   "settings": {"agent_speaks_first": true, "max_assistant_turns": 50}
	// }
	// ```
	//
	// **`type=connection`**, your own HTTP endpoint:
	// - `agent_url`: public HTTP(S) endpoint your agent is called at
	// - `agent_headers`: headers sent on each request, e.g. auth
	// - `benchmark_provider`: `openrouter` by default. Other values: `openai`, `google`, `anthropic`, `meta-llama`, `mistralai`, `deepseek`, `x-ai`, `cohere`, `qwen`, or `ai21`
	//
	// ```json
	// {
	//   "agent_url": "https://api.example.com/agent",
	//   "agent_headers": {"Authorization": "Bearer <token>"},
	//   "benchmark_provider": "openrouter"
	// }
	// ```
	//
	// Replaces the stored config. Omit to leave unchanged
	//
	// For `type=connection`, changing `agent_url` or `agent_headers` resets the connection and benchmark verification flags
	Config optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
}

func (a AgentUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentUpdate) GetName() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AgentUpdate) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if a == nil {
		return nil
	}
	return a.Config
}
