// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentTestsBulkUnlinkResponse struct {
	// Number of links removed. Tests that were not linked are excluded
	DeletedCount int64 `json:"deleted_count"`
	// Confirmation message
	Message string `json:"message"`
}

func (a *AgentTestsBulkUnlinkResponse) GetDeletedCount() int64 {
	if a == nil {
		return 0
	}
	return a.DeletedCount
}

func (a *AgentTestsBulkUnlinkResponse) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}
