// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentCreateResponse struct {
	// ID of the newly created agent
	UUID string `json:"uuid"`
	// Human-readable confirmation message
	Message string `json:"message"`
}

func (a *AgentCreateResponse) GetUUID() string {
	if a == nil {
		return ""
	}
	return a.UUID
}

func (a *AgentCreateResponse) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}
