// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
)

// AgentSummaryType - - `agent`: built inside Calibrate
// - `connection`: your existing agent connected to Calibrate
type AgentSummaryType string

const (
	AgentSummaryTypeAgent      AgentSummaryType = "agent"
	AgentSummaryTypeConnection AgentSummaryType = "connection"
)

func (e AgentSummaryType) ToPointer() *AgentSummaryType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentSummaryType) IsExact() bool {
	if e != nil {
		switch *e {
		case "agent", "connection":
			return true
		}
	}
	return false
}

// AgentSummaryInteractionType - What the agent expects in the request body:
//
// - `conversation`: a normal back-and-forth agent, answers within an ongoing conversation. Receives `{"messages": [...]}`
// - `general`: a one-shot agent, takes a single plain input and produces a single plain output, no conversation. Receives `{"input": "..."}`
type AgentSummaryInteractionType string

const (
	AgentSummaryInteractionTypeConversation AgentSummaryInteractionType = "conversation"
	AgentSummaryInteractionTypeGeneral      AgentSummaryInteractionType = "general"
)

func (e AgentSummaryInteractionType) ToPointer() *AgentSummaryInteractionType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentSummaryInteractionType) IsExact() bool {
	if e != nil {
		switch *e {
		case "conversation", "general":
			return true
		}
	}
	return false
}

type AgentSummary struct {
	// ID of the agent
	UUID string `json:"uuid"`
	// Name of the agent
	Name string `json:"name"`
	// - `agent`: built inside Calibrate
	// - `connection`: your existing agent connected to Calibrate
	Type AgentSummaryType `json:"type"`
	// What the agent expects in the request body:
	//
	// - `conversation`: a normal back-and-forth agent, answers within an ongoing conversation. Receives `{"messages": [...]}`
	// - `general`: a one-shot agent, takes a single plain input and produces a single plain output, no conversation. Receives `{"input": "..."}`
	InteractionType AgentSummaryInteractionType `json:"interaction_type"`
	// When the agent was created (ISO 8601 UTC)
	CreatedAt string `json:"created_at"`
	// When the agent was last updated (ISO 8601 UTC)
	UpdatedAt string `json:"updated_at"`
	// Whether the agent's connection has been verified, for a `type=connection` agent
	ConnectionVerified optionalnullable.OptionalNullable[bool] `json:"connection_verified,omitzero"`
	// Whether the agent has custom request fields configured
	HasDefaultInputs bool `json:"has_default_inputs"`
}

func (a *AgentSummary) GetUUID() string {
	if a == nil {
		return ""
	}
	return a.UUID
}

func (a *AgentSummary) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AgentSummary) GetType() AgentSummaryType {
	if a == nil {
		return AgentSummaryType("")
	}
	return a.Type
}

func (a *AgentSummary) GetInteractionType() AgentSummaryInteractionType {
	if a == nil {
		return AgentSummaryInteractionType("")
	}
	return a.InteractionType
}

func (a *AgentSummary) GetCreatedAt() string {
	if a == nil {
		return ""
	}
	return a.CreatedAt
}

func (a *AgentSummary) GetUpdatedAt() string {
	if a == nil {
		return ""
	}
	return a.UpdatedAt
}

func (a *AgentSummary) GetConnectionVerified() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.ConnectionVerified
}

func (a *AgentSummary) GetHasDefaultInputs() bool {
	if a == nil {
		return false
	}
	return a.HasDefaultInputs
}
