// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentTestRunCreateResponse struct {
	// Test run job ID. Poll for status and results
	TaskID string     `json:"task_id"`
	Status TaskStatus `json:"status"`
}

func (a *AgentTestRunCreateResponse) GetTaskID() string {
	if a == nil {
		return ""
	}
	return a.TaskID
}

func (a *AgentTestRunCreateResponse) GetStatus() TaskStatus {
	if a == nil {
		return TaskStatus("")
	}
	return a.Status
}
