// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentTestsCreateResponse struct {
	// Confirmation message
	Message string `json:"message"`
}

func (a *AgentTestsCreateResponse) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}
