// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// AgentVerifyRequest - Body for verifying an existing agent by ID. The endpoint (`agent_url`,
// `agent_headers`) comes from the agent's stored config, so only the probe
// inputs are accepted here.
type AgentVerifyRequest struct {
	// Model to verify. Omit for a basic connection check. Provide it for a model-specific check before benchmarking that model
	Model optionalnullable.OptionalNullable[string] `json:"model,omitzero"`
	// Sample chat messages to send during verification. Omit to use the default probe
	Messages optionalnullable.OptionalNullable[[]map[string]string] `json:"messages,omitzero"`
}

func (a AgentVerifyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentVerifyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentVerifyRequest) GetModel() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Model
}

func (a *AgentVerifyRequest) GetMessages() optionalnullable.OptionalNullable[[]map[string]string] {
	if a == nil {
		return nil
	}
	return a.Messages
}
