// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentTestsCreate struct {
	// Agent to link tests to
	AgentUUID string `json:"agent_uuid"`
	// Tests to link. Any that are already linked are skipped
	TestUuids []string `json:"test_uuids"`
}

func (a *AgentTestsCreate) GetAgentUUID() string {
	if a == nil {
		return ""
	}
	return a.AgentUUID
}

func (a *AgentTestsCreate) GetTestUuids() []string {
	if a == nil {
		return []string{}
	}
	return a.TestUuids
}
