// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnnotatorCreateResponse struct {
	// ID of the newly created annotator
	UUID string `json:"uuid"`
	// Success message
	Message string `json:"message"`
}

func (a *AnnotatorCreateResponse) GetUUID() string {
	if a == nil {
		return ""
	}
	return a.UUID
}

func (a *AnnotatorCreateResponse) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}
