// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
)

type AnnotatorResponse struct {
	// Annotator ID
	UUID string `json:"uuid"`
	// Annotator name
	Name string `json:"name"`
	// When the annotator was created (ISO 8601 UTC)
	CreatedAt string `json:"created_at"`
	// When the annotator was last updated (ISO 8601 UTC)
	UpdatedAt string `json:"updated_at"`
	// Number of labelling jobs assigned to this annotator
	JobsCount optionalnullable.OptionalNullable[int64] `json:"jobs_count,omitzero"`
	// Latest pairwise mean agreement with other annotators, from 0 to 1
	CurrentAgreement optionalnullable.OptionalNullable[float64] `json:"current_agreement,omitzero"`
	// Number of comparable annotation pairs behind the current agreement score
	PairCount optionalnullable.OptionalNullable[int64] `json:"pair_count,omitzero"`
}

func (a *AnnotatorResponse) GetUUID() string {
	if a == nil {
		return ""
	}
	return a.UUID
}

func (a *AnnotatorResponse) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AnnotatorResponse) GetCreatedAt() string {
	if a == nil {
		return ""
	}
	return a.CreatedAt
}

func (a *AnnotatorResponse) GetUpdatedAt() string {
	if a == nil {
		return ""
	}
	return a.UpdatedAt
}

func (a *AnnotatorResponse) GetJobsCount() optionalnullable.OptionalNullable[int64] {
	if a == nil {
		return nil
	}
	return a.JobsCount
}

func (a *AnnotatorResponse) GetCurrentAgreement() optionalnullable.OptionalNullable[float64] {
	if a == nil {
		return nil
	}
	return a.CurrentAgreement
}

func (a *AnnotatorResponse) GetPairCount() optionalnullable.OptionalNullable[int64] {
	if a == nil {
		return nil
	}
	return a.PairCount
}
