// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// AnnotationTaskCreateType - Task type. Determines the shape of each item's payload.
// - `stt`: judge a transcript on its own
// - `llm`: judge one response with its conversation history
// - `llm-general`: judge a standalone `input -> output` pair
// - `conversation`: judge a full conversation
type AnnotationTaskCreateType string

const (
	AnnotationTaskCreateTypeStt          AnnotationTaskCreateType = "stt"
	AnnotationTaskCreateTypeLlm          AnnotationTaskCreateType = "llm"
	AnnotationTaskCreateTypeLlmGeneral   AnnotationTaskCreateType = "llm-general"
	AnnotationTaskCreateTypeConversation AnnotationTaskCreateType = "conversation"
	AnnotationTaskCreateTypeTts          AnnotationTaskCreateType = "tts"
)

func (e AnnotationTaskCreateType) ToPointer() *AnnotationTaskCreateType {
	return &e
}
func (e *AnnotationTaskCreateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stt":
		fallthrough
	case "llm":
		fallthrough
	case "llm-general":
		fallthrough
	case "conversation":
		fallthrough
	case "tts":
		*e = AnnotationTaskCreateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnnotationTaskCreateType: %v", v)
	}
}

type AnnotationTaskCreate struct {
	// Task name, unique within your workspace
	Name string `json:"name"`
	// Task type. Determines the shape of each item's payload.
	// - `stt`: judge a transcript on its own
	// - `llm`: judge one response with its conversation history
	// - `llm-general`: judge a standalone `input -> output` pair
	// - `conversation`: judge a full conversation
	Type AnnotationTaskCreateType `json:"type"`
	// A description for the task. Omit for none
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// IDs of evaluators to link when the task is created, in order. Each must be one you created or a built-in default. Omit to create with no linked evaluators
	EvaluatorIds optionalnullable.OptionalNullable[[]string] `json:"evaluator_ids,omitzero"`
}

func (a AnnotationTaskCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnnotationTaskCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnnotationTaskCreate) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AnnotationTaskCreate) GetType() AnnotationTaskCreateType {
	if a == nil {
		return AnnotationTaskCreateType("")
	}
	return a.Type
}

func (a *AnnotationTaskCreate) GetDescription() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AnnotationTaskCreate) GetEvaluatorIds() optionalnullable.OptionalNullable[[]string] {
	if a == nil {
		return nil
	}
	return a.EvaluatorIds
}
