// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
)

type AnnotatorUpdate struct {
	// New annotator name, unique within your workspace. Omit to leave unchanged
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
}

func (a *AnnotatorUpdate) GetName() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Name
}
