// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// AnnotationTaskResponseType - Task type. Determines the shape of each item's payload.
// - `stt`: judge a transcript on its own
// - `tts`: judge synthesized speech output
// - `llm`: judge one response with its conversation history
// - `llm-general`: judge a standalone `input -> output` pair
// - `conversation`: judge a full conversation
type AnnotationTaskResponseType string

const (
	AnnotationTaskResponseTypeStt          AnnotationTaskResponseType = "stt"
	AnnotationTaskResponseTypeTts          AnnotationTaskResponseType = "tts"
	AnnotationTaskResponseTypeLlm          AnnotationTaskResponseType = "llm"
	AnnotationTaskResponseTypeLlmGeneral   AnnotationTaskResponseType = "llm-general"
	AnnotationTaskResponseTypeConversation AnnotationTaskResponseType = "conversation"
)

func (e AnnotationTaskResponseType) ToPointer() *AnnotationTaskResponseType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AnnotationTaskResponseType) IsExact() bool {
	if e != nil {
		switch *e {
		case "stt", "tts", "llm", "llm-general", "conversation":
			return true
		}
	}
	return false
}

type AnnotationTaskResponse struct {
	// Unique ID for the task
	UUID string `json:"uuid"`
	// Name of the task
	Name string `json:"name"`
	// Task type. Determines the shape of each item's payload.
	// - `stt`: judge a transcript on its own
	// - `tts`: judge synthesized speech output
	// - `llm`: judge one response with its conversation history
	// - `llm-general`: judge a standalone `input -> output` pair
	// - `conversation`: judge a full conversation
	Type AnnotationTaskResponseType `json:"type"`
	// The task's description
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// When the task was created (ISO 8601 UTC)
	CreatedAt string `json:"created_at"`
	// When the task was last updated (ISO 8601 UTC)
	UpdatedAt string `json:"updated_at"`
	// The evaluators linked to this task, in display order, each with its live version's rubric
	Evaluators []map[string]any `json:"evaluators,omitzero"`
	// Number of items in the task
	ItemCount optionalnullable.OptionalNullable[int64] `json:"item_count,omitzero"`
	// The task's items, each with its agreement stats. You get these when you fetch one task by ID, not when you list tasks
	Items []map[string]any `json:"items,omitzero"`
	// The task's labelling jobs. You get these when you fetch one task by ID, not when you list tasks
	Jobs []map[string]any `json:"jobs,omitzero"`
}

func (a AnnotationTaskResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnnotationTaskResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnnotationTaskResponse) GetUUID() string {
	if a == nil {
		return ""
	}
	return a.UUID
}

func (a *AnnotationTaskResponse) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AnnotationTaskResponse) GetType() AnnotationTaskResponseType {
	if a == nil {
		return AnnotationTaskResponseType("")
	}
	return a.Type
}

func (a *AnnotationTaskResponse) GetDescription() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AnnotationTaskResponse) GetCreatedAt() string {
	if a == nil {
		return ""
	}
	return a.CreatedAt
}

func (a *AnnotationTaskResponse) GetUpdatedAt() string {
	if a == nil {
		return ""
	}
	return a.UpdatedAt
}

func (a *AnnotationTaskResponse) GetEvaluators() []map[string]any {
	if a == nil {
		return nil
	}
	return a.Evaluators
}

func (a *AnnotationTaskResponse) GetItemCount() optionalnullable.OptionalNullable[int64] {
	if a == nil {
		return nil
	}
	return a.ItemCount
}

func (a *AnnotationTaskResponse) GetItems() []map[string]any {
	if a == nil {
		return nil
	}
	return a.Items
}

func (a *AnnotationTaskResponse) GetJobs() []map[string]any {
	if a == nil {
		return nil
	}
	return a.Jobs
}
