// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnnotatorCreate struct {
	// Annotator name, unique within your workspace
	Name string `json:"name"`
}

func (a *AnnotatorCreate) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}
