// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BatchTestRun struct {
	// Name of the agent
	AgentName string `json:"agent_name"`
	// ID of the agent that was run
	AgentUUID string `json:"agent_uuid"`
	// Test run job ID. Poll for status and results
	TaskID string     `json:"task_id"`
	Status TaskStatus `json:"status"`
}

func (b *BatchTestRun) GetAgentName() string {
	if b == nil {
		return ""
	}
	return b.AgentName
}

func (b *BatchTestRun) GetAgentUUID() string {
	if b == nil {
		return ""
	}
	return b.AgentUUID
}

func (b *BatchTestRun) GetTaskID() string {
	if b == nil {
		return ""
	}
	return b.TaskID
}

func (b *BatchTestRun) GetStatus() TaskStatus {
	if b == nil {
		return TaskStatus("")
	}
	return b.Status
}
