// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BatchTestSkip struct {
	// Name of the skipped agent
	AgentName string `json:"agent_name"`
	// ID of the skipped agent
	AgentUUID string `json:"agent_uuid"`
	// Why this agent was not run
	Reason string `json:"reason"`
}

func (b *BatchTestSkip) GetAgentName() string {
	if b == nil {
		return ""
	}
	return b.AgentName
}

func (b *BatchTestSkip) GetAgentUUID() string {
	if b == nil {
		return ""
	}
	return b.AgentUUID
}

func (b *BatchTestSkip) GetReason() string {
	if b == nil {
		return ""
	}
	return b.Reason
}
