// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BatchTestRunStatus - Current status of the run
type BatchTestRunStatus string

const (
	BatchTestRunStatusQueued     BatchTestRunStatus = "queued"
	BatchTestRunStatusInProgress BatchTestRunStatus = "in_progress"
)

func (e BatchTestRunStatus) ToPointer() *BatchTestRunStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BatchTestRunStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "queued", "in_progress":
			return true
		}
	}
	return false
}

type BatchTestRun struct {
	// Name of the agent
	AgentName string `json:"agent_name"`
	// ID of the agent that was run
	AgentUUID string `json:"agent_uuid"`
	// Test run job ID. Poll it for status and results
	TaskID string `json:"task_id"`
	// Current status of the run
	Status BatchTestRunStatus `json:"status"`
}

func (b *BatchTestRun) GetAgentName() string {
	if b == nil {
		return ""
	}
	return b.AgentName
}

func (b *BatchTestRun) GetAgentUUID() string {
	if b == nil {
		return ""
	}
	return b.AgentUUID
}

func (b *BatchTestRun) GetTaskID() string {
	if b == nil {
		return ""
	}
	return b.TaskID
}

func (b *BatchTestRun) GetStatus() BatchTestRunStatus {
	if b == nil {
		return BatchTestRunStatus("")
	}
	return b.Status
}
