// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Reason - Why this agent was not run:
// - `no_linked_tests`: the agent has no tests linked
// - `connection_not_verified`: the agent's connection is not verified
// - `over_row_limit`: the agent has more linked tests than this workspace allows in one run
type Reason string

const (
	ReasonNoLinkedTests         Reason = "no_linked_tests"
	ReasonConnectionNotVerified Reason = "connection_not_verified"
	ReasonOverRowLimit          Reason = "over_row_limit"
)

func (e Reason) ToPointer() *Reason {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Reason) IsExact() bool {
	if e != nil {
		switch *e {
		case "no_linked_tests", "connection_not_verified", "over_row_limit":
			return true
		}
	}
	return false
}

type BatchTestSkip struct {
	// Name of the skipped agent
	AgentName string `json:"agent_name"`
	// ID of the skipped agent
	AgentUUID string `json:"agent_uuid"`
	// Why this agent was not run:
	// - `no_linked_tests`: the agent has no tests linked
	// - `connection_not_verified`: the agent's connection is not verified
	// - `over_row_limit`: the agent has more linked tests than this workspace allows in one run
	Reason Reason `json:"reason"`
}

func (b *BatchTestSkip) GetAgentName() string {
	if b == nil {
		return ""
	}
	return b.AgentName
}

func (b *BatchTestSkip) GetAgentUUID() string {
	if b == nil {
		return ""
	}
	return b.AgentUUID
}

func (b *BatchTestSkip) GetReason() Reason {
	if b == nil {
		return Reason("")
	}
	return b.Reason
}
