// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BulkUpdateItemsResponse struct {
	// How many items were updated
	UpdatedCount int64 `json:"updated_count"`
}

func (b *BulkUpdateItemsResponse) GetUpdatedCount() int64 {
	if b == nil {
		return 0
	}
	return b.UpdatedCount
}
