// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type BulkCreateItemsResponse struct {
	// IDs of every item the request resolved to, in request order
	ItemIds []string `json:"item_ids"`
	// How many items the request resolved to
	Count int64 `json:"count"`
	// IDs of the items that were newly created
	NewItemIds optionalnullable.OptionalNullable[[]string] `json:"new_item_ids,omitzero"`
	// IDs of items that already existed by name and were reused
	ExistingItemIds optionalnullable.OptionalNullable[[]string] `json:"existing_item_ids,omitzero"`
	// ID of the labelling job that holds the annotations you provided, present only when you send annotations with the items
	AnnotationJobID optionalnullable.OptionalNullable[string] `json:"annotation_job_id,omitzero"`
	// How many evaluator scores were stored, present only when you send `evaluator_results` with the items
	EvaluatorResultCount optionalnullable.OptionalNullable[int64] `json:"evaluator_result_count,omitzero"`
	// ID of the evaluator-run job that holds the scores you provided, present only when you send `evaluator_results` with the items
	EvaluatorRunJobID optionalnullable.OptionalNullable[string] `json:"evaluator_run_job_id,omitzero"`
}

func (b BulkCreateItemsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkCreateItemsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkCreateItemsResponse) GetItemIds() []string {
	if b == nil {
		return []string{}
	}
	return b.ItemIds
}

func (b *BulkCreateItemsResponse) GetCount() int64 {
	if b == nil {
		return 0
	}
	return b.Count
}

func (b *BulkCreateItemsResponse) GetNewItemIds() optionalnullable.OptionalNullable[[]string] {
	if b == nil {
		return nil
	}
	return b.NewItemIds
}

func (b *BulkCreateItemsResponse) GetExistingItemIds() optionalnullable.OptionalNullable[[]string] {
	if b == nil {
		return nil
	}
	return b.ExistingItemIds
}

func (b *BulkCreateItemsResponse) GetAnnotationJobID() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.AnnotationJobID
}

func (b *BulkCreateItemsResponse) GetEvaluatorResultCount() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.EvaluatorResultCount
}

func (b *BulkCreateItemsResponse) GetEvaluatorRunJobID() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.EvaluatorRunJobID
}
