// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type BulkTestItem struct {
	// Name of the test, unique within the workspace and within the batch
	Name string `json:"name"`
	// Ordered messages ending at the user turn the agent should answer (must be non-empty)
	ConversationHistory []ChatMessage `json:"conversation_history"`
	// Evaluators to link. Used by `response` and `conversation` tests
	Evaluators optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] `json:"evaluators,omitzero"`
	// Expected tool calls. **Required for `tool_call` batches**
	ToolCalls optionalnullable.OptionalNullable[[]ExpectedToolCall] `json:"tool_calls,omitzero"`
}

func (b BulkTestItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkTestItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkTestItem) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BulkTestItem) GetConversationHistory() []ChatMessage {
	if b == nil {
		return []ChatMessage{}
	}
	return b.ConversationHistory
}

func (b *BulkTestItem) GetEvaluators() optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] {
	if b == nil {
		return nil
	}
	return b.Evaluators
}

func (b *BulkTestItem) GetToolCalls() optionalnullable.OptionalNullable[[]ExpectedToolCall] {
	if b == nil {
		return nil
	}
	return b.ToolCalls
}
