// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// Role - Message author role in the conversation history
type Role string

const (
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
	RoleTool      Role = "tool"
)

func (e Role) ToPointer() *Role {
	return &e
}
func (e *Role) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		fallthrough
	case "assistant":
		fallthrough
	case "tool":
		*e = Role(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Role: %v", v)
	}
}

type ChatMessage struct {
	// Message author role in the conversation history
	Role Role `json:"role"`
	// Message text. Omit for assistant messages that only carry `tool_calls`
	Content optionalnullable.OptionalNullable[string] `json:"content,omitzero"`
	// Tool calls issued by the assistant. Omit for plain text turns
	ToolCalls optionalnullable.OptionalNullable[[]map[string]any] `json:"tool_calls,omitzero"`
	// ID of the tool call this message responds to. **Required for `role=tool`**
	ToolCallID optionalnullable.OptionalNullable[string] `json:"tool_call_id,omitzero"`
	// Tool name for `role=tool` messages. Omit otherwise
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
}

func (c ChatMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatMessage) GetRole() Role {
	if c == nil {
		return Role("")
	}
	return c.Role
}

func (c *ChatMessage) GetContent() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Content
}

func (c *ChatMessage) GetToolCalls() optionalnullable.OptionalNullable[[]map[string]any] {
	if c == nil {
		return nil
	}
	return c.ToolCalls
}

func (c *ChatMessage) GetToolCallID() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ToolCallID
}

func (c *ChatMessage) GetName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Name
}
