// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type CreateJobsRequest struct {
	// Annotator IDs to assign, creating one labelling job for each annotator. Must be in your workspace
	AnnotatorIds []string `json:"annotator_ids"`
	// Item IDs to assign. **Required when `select_all=false`**. Ignored when `select_all=true`
	ItemIds []string `json:"item_ids,omitzero"`
	// When `true`, assign every item in the task and ignore `item_ids`. Set `q` to assign only items whose name matches it
	SelectAll *bool `default:"false" json:"select_all"`
	// Case-insensitive substring filter on `payload.name`. Applies only when `select_all=true`
	Q optionalnullable.OptionalNullable[string] `json:"q,omitzero"`
	// Subset of the task's linked evaluators to show in these jobs. Must be a subset of the current links, an empty list gives a 400. Applies to every annotator's job. Omit (`None`) to snapshot every linked evaluator
	EvaluatorIds optionalnullable.OptionalNullable[[]string] `json:"evaluator_ids,omitzero"`
}

func (c CreateJobsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateJobsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateJobsRequest) GetAnnotatorIds() []string {
	if c == nil {
		return []string{}
	}
	return c.AnnotatorIds
}

func (c *CreateJobsRequest) GetItemIds() []string {
	if c == nil {
		return nil
	}
	return c.ItemIds
}

func (c *CreateJobsRequest) GetSelectAll() *bool {
	if c == nil {
		return nil
	}
	return c.SelectAll
}

func (c *CreateJobsRequest) GetQ() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Q
}

func (c *CreateJobsRequest) GetEvaluatorIds() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.EvaluatorIds
}
