// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateJobsResponse struct {
	// The jobs created, one for each annotator
	Jobs []LabellingJobCreated `json:"jobs"`
	// How many jobs were created
	Count int64 `json:"count"`
}

func (c *CreateJobsResponse) GetJobs() []LabellingJobCreated {
	if c == nil {
		return []LabellingJobCreated{}
	}
	return c.Jobs
}

func (c *CreateJobsResponse) GetCount() int64 {
	if c == nil {
		return 0
	}
	return c.Count
}
