// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// EvaluatorCreateEvaluatorType - What the evaluator judges:
//
// - `tts`: TTS audio
// - `stt`: one transcript
// - `llm`: a reply with its conversation history
// - `llm-general`: a standalone input and output pair
// - `conversation`: a full conversation
type EvaluatorCreateEvaluatorType string

const (
	EvaluatorCreateEvaluatorTypeTts          EvaluatorCreateEvaluatorType = "tts"
	EvaluatorCreateEvaluatorTypeStt          EvaluatorCreateEvaluatorType = "stt"
	EvaluatorCreateEvaluatorTypeLlm          EvaluatorCreateEvaluatorType = "llm"
	EvaluatorCreateEvaluatorTypeLlmGeneral   EvaluatorCreateEvaluatorType = "llm-general"
	EvaluatorCreateEvaluatorTypeConversation EvaluatorCreateEvaluatorType = "conversation"
)

func (e EvaluatorCreateEvaluatorType) ToPointer() *EvaluatorCreateEvaluatorType {
	return &e
}
func (e *EvaluatorCreateEvaluatorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tts":
		fallthrough
	case "stt":
		fallthrough
	case "llm":
		fallthrough
	case "llm-general":
		fallthrough
	case "conversation":
		*e = EvaluatorCreateEvaluatorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EvaluatorCreateEvaluatorType: %v", v)
	}
}

// EvaluatorCreateDataType - The modality the judge reads:
//
// - `text`
// - `audio`
type EvaluatorCreateDataType string

const (
	EvaluatorCreateDataTypeText  EvaluatorCreateDataType = "text"
	EvaluatorCreateDataTypeAudio EvaluatorCreateDataType = "audio"
)

func (e EvaluatorCreateDataType) ToPointer() *EvaluatorCreateDataType {
	return &e
}
func (e *EvaluatorCreateDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "audio":
		*e = EvaluatorCreateDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EvaluatorCreateDataType: %v", v)
	}
}

// EvaluatorCreateOutputType - How the evaluator scores:
//
// - `binary`: pass or fail
// - `rating`: a numeric score, using the scale in `output_config`
type EvaluatorCreateOutputType string

const (
	EvaluatorCreateOutputTypeBinary EvaluatorCreateOutputType = "binary"
	EvaluatorCreateOutputTypeRating EvaluatorCreateOutputType = "rating"
)

func (e EvaluatorCreateOutputType) ToPointer() *EvaluatorCreateOutputType {
	return &e
}
func (e *EvaluatorCreateOutputType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "binary":
		fallthrough
	case "rating":
		*e = EvaluatorCreateOutputType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EvaluatorCreateOutputType: %v", v)
	}
}

type EvaluatorCreate struct {
	// Evaluator name, unique within your workspace
	Name string `json:"name"`
	// Description. Omit to leave blank
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// What the evaluator judges:
	//
	// - `tts`: TTS audio
	// - `stt`: one transcript
	// - `llm`: a reply with its conversation history
	// - `llm-general`: a standalone input and output pair
	// - `conversation`: a full conversation
	//
	EvaluatorType *EvaluatorCreateEvaluatorType `default:"llm" json:"evaluator_type"`
	// The modality the judge reads:
	//
	// - `text`
	// - `audio`
	//
	DataType *EvaluatorCreateDataType `default:"text" json:"data_type"`
	// How the evaluator scores:
	//
	// - `binary`: pass or fail
	// - `rating`: a numeric score, using the scale in `output_config`
	//
	OutputType *EvaluatorCreateOutputType `default:"binary" json:"output_type"`
	// One version of an evaluator: its judge prompt, model, variables, and rubric.
	Version EvaluatorVersionCreate `json:"version"`
}

func (e EvaluatorCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvaluatorCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvaluatorCreate) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EvaluatorCreate) GetDescription() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *EvaluatorCreate) GetEvaluatorType() *EvaluatorCreateEvaluatorType {
	if e == nil {
		return nil
	}
	return e.EvaluatorType
}

func (e *EvaluatorCreate) GetDataType() *EvaluatorCreateDataType {
	if e == nil {
		return nil
	}
	return e.DataType
}

func (e *EvaluatorCreate) GetOutputType() *EvaluatorCreateOutputType {
	if e == nil {
		return nil
	}
	return e.OutputType
}

func (e *EvaluatorCreate) GetVersion() EvaluatorVersionCreate {
	if e == nil {
		return EvaluatorVersionCreate{}
	}
	return e.Version
}
