// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EvaluatorSetResponse struct {
	// Confirmation that the task's evaluators were updated
	Message string `json:"message"`
	// The task's evaluator IDs after the update, in display order
	EvaluatorIds []string `json:"evaluator_ids"`
	// Evaluator IDs newly linked by this request
	Linked []string `json:"linked"`
	// Evaluator IDs unlinked by this request
	Unlinked []string `json:"unlinked"`
}

func (e *EvaluatorSetResponse) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *EvaluatorSetResponse) GetEvaluatorIds() []string {
	if e == nil {
		return []string{}
	}
	return e.EvaluatorIds
}

func (e *EvaluatorSetResponse) GetLinked() []string {
	if e == nil {
		return []string{}
	}
	return e.Linked
}

func (e *EvaluatorSetResponse) GetUnlinked() []string {
	if e == nil {
		return []string{}
	}
	return e.Unlinked
}
