// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
)

type EvaluatorRunRequestEntry struct {
	// Evaluator ID to run. Must be linked to the task
	EvaluatorID string `json:"evaluator_id"`
	// Evaluator version ID to run. Omit to use the evaluator's live version
	EvaluatorVersionID optionalnullable.OptionalNullable[string] `json:"evaluator_version_id,omitzero"`
}

func (e *EvaluatorRunRequestEntry) GetEvaluatorID() string {
	if e == nil {
		return ""
	}
	return e.EvaluatorID
}

func (e *EvaluatorRunRequestEntry) GetEvaluatorVersionID() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.EvaluatorVersionID
}
