// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EvaluatorSetRequest struct {
	// The full ordered set of evaluators the task should end up linked to, in display order. Missing ones are unlinked, new ones are linked, and the order sets their position. Send an empty list to unlink all. Each must be one you created or a built-in default
	EvaluatorIds []string `json:"evaluator_ids"`
}

func (e *EvaluatorSetRequest) GetEvaluatorIds() []string {
	if e == nil {
		return []string{}
	}
	return e.EvaluatorIds
}
