// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EvaluatorRunLaunchResponseStatus - Status of the job right after you launch it
type EvaluatorRunLaunchResponseStatus string

const (
	EvaluatorRunLaunchResponseStatusQueued     EvaluatorRunLaunchResponseStatus = "queued"
	EvaluatorRunLaunchResponseStatusInProgress EvaluatorRunLaunchResponseStatus = "in_progress"
)

func (e EvaluatorRunLaunchResponseStatus) ToPointer() *EvaluatorRunLaunchResponseStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EvaluatorRunLaunchResponseStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "queued", "in_progress":
			return true
		}
	}
	return false
}

type EvaluatorRunLaunchResponse struct {
	// ID of the evaluator-run job. Poll it for status and results
	JobUUID string `json:"job_uuid"`
	// Status of the job right after you launch it
	Status EvaluatorRunLaunchResponseStatus `json:"status"`
	// How many evaluators the job will run
	EvaluatorCount int64 `json:"evaluator_count"`
	// How many items the job will run on
	ItemCount int64 `json:"item_count"`
}

func (e *EvaluatorRunLaunchResponse) GetJobUUID() string {
	if e == nil {
		return ""
	}
	return e.JobUUID
}

func (e *EvaluatorRunLaunchResponse) GetStatus() EvaluatorRunLaunchResponseStatus {
	if e == nil {
		return EvaluatorRunLaunchResponseStatus("")
	}
	return e.Status
}

func (e *EvaluatorRunLaunchResponse) GetEvaluatorCount() int64 {
	if e == nil {
		return 0
	}
	return e.EvaluatorCount
}

func (e *EvaluatorRunLaunchResponse) GetItemCount() int64 {
	if e == nil {
		return 0
	}
	return e.ItemCount
}
