// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type EvaluatorVersionCompact struct {
	// Version ID
	UUID string `json:"uuid"`
	// The version's number. The first version is 1, and it goes up by one for each new version of the evaluator
	VersionNumber int64 `json:"version_number"`
	// The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`
	JudgeModel string `json:"judge_model"`
	// Judge system prompt, with `{{variable}}` placeholders unrendered
	SystemPrompt optionalnullable.OptionalNullable[string] `json:"system_prompt,omitzero"`
	// The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own
	OutputConfig optionalnullable.OptionalNullable[OutputConfig] `json:"output_config,omitzero"`
	// Declared prompt variables
	Variables optionalnullable.OptionalNullable[[]VariableSpec] `json:"variables,omitzero"`
	// When the version was created (ISO 8601 UTC)
	CreatedAt string `json:"created_at"`
}

func (e EvaluatorVersionCompact) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvaluatorVersionCompact) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvaluatorVersionCompact) GetUUID() string {
	if e == nil {
		return ""
	}
	return e.UUID
}

func (e *EvaluatorVersionCompact) GetVersionNumber() int64 {
	if e == nil {
		return 0
	}
	return e.VersionNumber
}

func (e *EvaluatorVersionCompact) GetJudgeModel() string {
	if e == nil {
		return ""
	}
	return e.JudgeModel
}

func (e *EvaluatorVersionCompact) GetSystemPrompt() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.SystemPrompt
}

func (e *EvaluatorVersionCompact) GetOutputConfig() optionalnullable.OptionalNullable[OutputConfig] {
	if e == nil {
		return nil
	}
	return e.OutputConfig
}

func (e *EvaluatorVersionCompact) GetVariables() optionalnullable.OptionalNullable[[]VariableSpec] {
	if e == nil {
		return nil
	}
	return e.Variables
}

func (e *EvaluatorVersionCompact) GetCreatedAt() string {
	if e == nil {
		return ""
	}
	return e.CreatedAt
}
