// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type EvaluatorSetRequest struct {
	// The full ordered set of evaluators the task should end up linked to, in display order. Missing ones are unlinked, new ones are linked, and the order sets their position. Send an empty list to unlink all. Each must be one you created or a built-in default
	EvaluatorIds []string `json:"evaluator_ids"`
	// Which of `evaluator_ids` annotators may leave blank. Applied as a whole set, so an ID left out becomes required again. Optional evaluators do not hold a labelling job back from completing. Omit to leave every evaluator as it is
	OptionalEvaluatorIds optionalnullable.OptionalNullable[[]string] `json:"optional_evaluator_ids,omitzero"`
}

func (e EvaluatorSetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvaluatorSetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvaluatorSetRequest) GetEvaluatorIds() []string {
	if e == nil {
		return []string{}
	}
	return e.EvaluatorIds
}

func (e *EvaluatorSetRequest) GetOptionalEvaluatorIds() optionalnullable.OptionalNullable[[]string] {
	if e == nil {
		return nil
	}
	return e.OptionalEvaluatorIds
}
