// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// EvaluatorVersionCreate - One version of an evaluator: its judge prompt, model, variables, and rubric.
type EvaluatorVersionCreate struct {
	// The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`
	JudgeModel string `json:"judge_model"`
	// Judge system prompt. May contain `{{variable}}` placeholders
	SystemPrompt string `json:"system_prompt"`
	// The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own
	OutputConfig optionalnullable.OptionalNullable[OutputConfig] `json:"output_config,omitzero"`
	// Declared prompt variables. Omit if the prompt has no `{{placeholders}}`
	Variables optionalnullable.OptionalNullable[[]VariableSpec] `json:"variables,omitzero"`
}

func (e EvaluatorVersionCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvaluatorVersionCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvaluatorVersionCreate) GetJudgeModel() string {
	if e == nil {
		return ""
	}
	return e.JudgeModel
}

func (e *EvaluatorVersionCreate) GetSystemPrompt() string {
	if e == nil {
		return ""
	}
	return e.SystemPrompt
}

func (e *EvaluatorVersionCreate) GetOutputConfig() optionalnullable.OptionalNullable[OutputConfig] {
	if e == nil {
		return nil
	}
	return e.OutputConfig
}

func (e *EvaluatorVersionCreate) GetVariables() optionalnullable.OptionalNullable[[]VariableSpec] {
	if e == nil {
		return nil
	}
	return e.Variables
}
