// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EvaluatorLinkResponse struct {
	// Confirmation that the evaluator was linked
	Message string `json:"message"`
}

func (e *EvaluatorLinkResponse) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}
