// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// EvaluatorVersionCreateRequest - Request body for adding a version to an existing evaluator.
type EvaluatorVersionCreateRequest struct {
	// The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`
	JudgeModel string `json:"judge_model"`
	// Judge system prompt. May contain `{{variable}}` placeholders
	SystemPrompt string `json:"system_prompt"`
	// The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own
	OutputConfig optionalnullable.OptionalNullable[OutputConfig] `json:"output_config,omitzero"`
	// Declared prompt variables. Omit if the prompt has none. After the first version the variable names are fixed. You can change a variable's description or default, but not add, remove, or rename one
	Variables optionalnullable.OptionalNullable[[]VariableSpec] `json:"variables,omitzero"`
	// When `true`, immediately point the evaluator's live version at this new version
	MakeLive *bool `default:"false" json:"make_live"`
}

func (e EvaluatorVersionCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvaluatorVersionCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvaluatorVersionCreateRequest) GetJudgeModel() string {
	if e == nil {
		return ""
	}
	return e.JudgeModel
}

func (e *EvaluatorVersionCreateRequest) GetSystemPrompt() string {
	if e == nil {
		return ""
	}
	return e.SystemPrompt
}

func (e *EvaluatorVersionCreateRequest) GetOutputConfig() optionalnullable.OptionalNullable[OutputConfig] {
	if e == nil {
		return nil
	}
	return e.OutputConfig
}

func (e *EvaluatorVersionCreateRequest) GetVariables() optionalnullable.OptionalNullable[[]VariableSpec] {
	if e == nil {
		return nil
	}
	return e.Variables
}

func (e *EvaluatorVersionCreateRequest) GetMakeLive() *bool {
	if e == nil {
		return nil
	}
	return e.MakeLive
}
