// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EvaluatorCreateResponse struct {
	// ID of the created evaluator
	UUID string `json:"uuid"`
	// ID of its initial version
	VersionUUID string `json:"version_uuid"`
}

func (e *EvaluatorCreateResponse) GetUUID() string {
	if e == nil {
		return ""
	}
	return e.UUID
}

func (e *EvaluatorCreateResponse) GetVersionUUID() string {
	if e == nil {
		return ""
	}
	return e.VersionUUID
}
