// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EvaluatorLinkResponse struct {
	// Confirmation that the evaluators were linked
	Message string `json:"message"`
	// Evaluator IDs newly linked by this request
	Linked []string `json:"linked"`
	// Evaluator IDs skipped because they were already linked
	AlreadyLinked []string `json:"already_linked"`
}

func (e *EvaluatorLinkResponse) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *EvaluatorLinkResponse) GetLinked() []string {
	if e == nil {
		return []string{}
	}
	return e.Linked
}

func (e *EvaluatorLinkResponse) GetAlreadyLinked() []string {
	if e == nil {
		return []string{}
	}
	return e.AlreadyLinked
}
