// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type HumanAgreementBlock struct {
	// Current mean pairwise agreement among annotators
	Current *float64 `json:"current"`
	// How many annotator pairs the current value averages over
	PairCount int64 `json:"pair_count"`
	// Agreement over time, one point per time bucket
	Series               []map[string]any `json:"series"`
	AdditionalProperties map[string]any   `additionalProperties:"true" json:"-"`
}

func (h HumanAgreementBlock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HumanAgreementBlock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HumanAgreementBlock) GetCurrent() *float64 {
	if h == nil {
		return nil
	}
	return h.Current
}

func (h *HumanAgreementBlock) GetPairCount() int64 {
	if h == nil {
		return 0
	}
	return h.PairCount
}

func (h *HumanAgreementBlock) GetSeries() []map[string]any {
	if h == nil {
		return []map[string]any{}
	}
	return h.Series
}

func (h *HumanAgreementBlock) GetAdditionalProperties() map[string]any {
	if h == nil {
		return nil
	}
	return h.AdditionalProperties
}
