// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type JudgeResult struct {
	// ID of the evaluator that produced this verdict
	EvaluatorUUID optionalnullable.OptionalNullable[string] `json:"evaluator_uuid,omitzero"`
	// Judge's rationale for this verdict
	Reasoning optionalnullable.OptionalNullable[string] `json:"reasoning,omitzero"`
	// Pass/fail verdict, for binary evaluators
	Match optionalnullable.OptionalNullable[bool] `json:"match,omitzero"`
	// Numeric score, for rating evaluators
	Score optionalnullable.OptionalNullable[float64] `json:"score,omitzero"`
	// Readable label for the verdict, from the run's rubric
	ValueName optionalnullable.OptionalNullable[string] `json:"value_name,omitzero"`
	// `{{var}}` substitutions used for this evaluator on this test case
	VariableValues optionalnullable.OptionalNullable[map[string]any] `json:"variable_values,omitzero"`
}

func (j JudgeResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JudgeResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *JudgeResult) GetEvaluatorUUID() optionalnullable.OptionalNullable[string] {
	if j == nil {
		return nil
	}
	return j.EvaluatorUUID
}

func (j *JudgeResult) GetReasoning() optionalnullable.OptionalNullable[string] {
	if j == nil {
		return nil
	}
	return j.Reasoning
}

func (j *JudgeResult) GetMatch() optionalnullable.OptionalNullable[bool] {
	if j == nil {
		return nil
	}
	return j.Match
}

func (j *JudgeResult) GetScore() optionalnullable.OptionalNullable[float64] {
	if j == nil {
		return nil
	}
	return j.Score
}

func (j *JudgeResult) GetValueName() optionalnullable.OptionalNullable[string] {
	if j == nil {
		return nil
	}
	return j.ValueName
}

func (j *JudgeResult) GetVariableValues() optionalnullable.OptionalNullable[map[string]any] {
	if j == nil {
		return nil
	}
	return j.VariableValues
}
