// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type LabellingJobCreated struct {
	// ID of the labelling job
	UUID string `json:"uuid"`
	// Token that opens the annotator's labelling page without signing in
	PublicToken string `json:"public_token"`
	// ID of the annotator the job is assigned to
	AnnotatorID string `json:"annotator_id"`
	// Name of the annotator the job is assigned to
	AnnotatorName string `json:"annotator_name"`
	// IDs of the items assigned to the annotator
	ItemIds []string `json:"item_ids"`
	// How many items the annotator has to label
	ItemCount int64 `json:"item_count"`
	// IDs of the evaluators the annotator scores each item on, in the order they are shown
	EvaluatorIds []string `json:"evaluator_ids"`
	// Status of the job right after you create it
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	status string `const:"pending" json:"status"`
}

func (l LabellingJobCreated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LabellingJobCreated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LabellingJobCreated) GetUUID() string {
	if l == nil {
		return ""
	}
	return l.UUID
}

func (l *LabellingJobCreated) GetPublicToken() string {
	if l == nil {
		return ""
	}
	return l.PublicToken
}

func (l *LabellingJobCreated) GetAnnotatorID() string {
	if l == nil {
		return ""
	}
	return l.AnnotatorID
}

func (l *LabellingJobCreated) GetAnnotatorName() string {
	if l == nil {
		return ""
	}
	return l.AnnotatorName
}

func (l *LabellingJobCreated) GetItemIds() []string {
	if l == nil {
		return []string{}
	}
	return l.ItemIds
}

func (l *LabellingJobCreated) GetItemCount() int64 {
	if l == nil {
		return 0
	}
	return l.ItemCount
}

func (l *LabellingJobCreated) GetEvaluatorIds() []string {
	if l == nil {
		return []string{}
	}
	return l.EvaluatorIds
}

func (l *LabellingJobCreated) GetStatus() string {
	return "pending"
}
