// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type ModelResult struct {
	// Model name these results are for
	Model string `json:"model"`
	// Whether this model's run succeeded
	Success optionalnullable.OptionalNullable[bool] `json:"success,omitzero"`
	// Status or result message for this model
	Message string `json:"message"`
	// Total test cases for this model
	TotalTests optionalnullable.OptionalNullable[int64] `json:"total_tests,omitzero"`
	// Number of test cases that passed
	Passed optionalnullable.OptionalNullable[int64] `json:"passed,omitzero"`
	// Number of test cases that failed
	Failed optionalnullable.OptionalNullable[int64] `json:"failed,omitzero"`
	// Aggregate summary for each evaluator for this model
	EvaluatorSummary optionalnullable.OptionalNullable[[]map[string]any] `json:"evaluator_summary,omitzero"`
	// Results for each test case for this model
	TestResults optionalnullable.OptionalNullable[[]TestCaseResult] `json:"test_results,omitzero"`
	// Aggregated latency in milliseconds, as `{p50, p95, p99, count}`
	LatencyMs optionalnullable.OptionalNullable[map[string]any] `json:"latency_ms,omitzero"`
	// Aggregated cost as `{mean, min, max, count}` (USD)
	Cost optionalnullable.OptionalNullable[map[string]any] `json:"cost,omitzero"`
	// Aggregated token usage as `{mean, min, max, count}`
	TotalTokens optionalnullable.OptionalNullable[map[string]any] `json:"total_tokens,omitzero"`
}

func (m ModelResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *ModelResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *ModelResult) GetModel() string {
	if m == nil {
		return ""
	}
	return m.Model
}

func (m *ModelResult) GetSuccess() optionalnullable.OptionalNullable[bool] {
	if m == nil {
		return nil
	}
	return m.Success
}

func (m *ModelResult) GetMessage() string {
	if m == nil {
		return ""
	}
	return m.Message
}

func (m *ModelResult) GetTotalTests() optionalnullable.OptionalNullable[int64] {
	if m == nil {
		return nil
	}
	return m.TotalTests
}

func (m *ModelResult) GetPassed() optionalnullable.OptionalNullable[int64] {
	if m == nil {
		return nil
	}
	return m.Passed
}

func (m *ModelResult) GetFailed() optionalnullable.OptionalNullable[int64] {
	if m == nil {
		return nil
	}
	return m.Failed
}

func (m *ModelResult) GetEvaluatorSummary() optionalnullable.OptionalNullable[[]map[string]any] {
	if m == nil {
		return nil
	}
	return m.EvaluatorSummary
}

func (m *ModelResult) GetTestResults() optionalnullable.OptionalNullable[[]TestCaseResult] {
	if m == nil {
		return nil
	}
	return m.TestResults
}

func (m *ModelResult) GetLatencyMs() optionalnullable.OptionalNullable[map[string]any] {
	if m == nil {
		return nil
	}
	return m.LatencyMs
}

func (m *ModelResult) GetCost() optionalnullable.OptionalNullable[map[string]any] {
	if m == nil {
		return nil
	}
	return m.Cost
}

func (m *ModelResult) GetTotalTokens() optionalnullable.OptionalNullable[map[string]any] {
	if m == nil {
		return nil
	}
	return m.TotalTokens
}
