// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type OutputConfig struct {
	// The ordered scale points that make up the rubric, each with its label
	Scale optionalnullable.OptionalNullable[[]OutputScaleEntry] `json:"scale,omitzero"`
}

func (o OutputConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputConfig) GetScale() optionalnullable.OptionalNullable[[]OutputScaleEntry] {
	if o == nil {
		return nil
	}
	return o.Scale
}
