// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
)

// OutputScaleEntry - One entry in an evaluator's output_config.scale. `value` is bool|number|string
// depending on output_type.
type OutputScaleEntry struct {
	// The value for this scale point. Use a boolean for a `binary` evaluator, a number for a `rating` one
	Value any `json:"value"`
	// Short label for this scale point
	Name string `json:"name"`
	// Rubric text for this level, added to the judge prompt. Omit to leave this level undescribed
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// Color to show for this level. Omit for the default
	Color optionalnullable.OptionalNullable[string] `json:"color,omitzero"`
}

func (o *OutputScaleEntry) GetValue() any {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *OutputScaleEntry) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OutputScaleEntry) GetDescription() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OutputScaleEntry) GetColor() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Color
}
