// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type PaginatedResponseAnnotationTaskResponse struct {
	// The page of results
	Items []AnnotationTaskResponse `json:"items"`
	// Total number of items matching the query, before pagination
	Total int64 `json:"total"`
	// The applied `limit` (null when unbounded)
	Limit optionalnullable.OptionalNullable[int64] `json:"limit,omitzero"`
	// The applied `offset`
	Offset *int64 `default:"0" json:"offset"`
}

func (p PaginatedResponseAnnotationTaskResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaginatedResponseAnnotationTaskResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaginatedResponseAnnotationTaskResponse) GetItems() []AnnotationTaskResponse {
	if p == nil {
		return []AnnotationTaskResponse{}
	}
	return p.Items
}

func (p *PaginatedResponseAnnotationTaskResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PaginatedResponseAnnotationTaskResponse) GetLimit() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PaginatedResponseAnnotationTaskResponse) GetOffset() *int64 {
	if p == nil {
		return nil
	}
	return p.Offset
}
