// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginationMeta struct {
	// Total number of items that match, across all pages
	Total int64 `json:"total"`
	// Maximum number of items returned in this page
	Limit int64 `json:"limit"`
	// Number of items skipped before this page
	Offset int64 `json:"offset"`
}

func (p *PaginationMeta) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PaginationMeta) GetLimit() int64 {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *PaginationMeta) GetOffset() int64 {
	if p == nil {
		return 0
	}
	return p.Offset
}
