// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResolveAgentNamesResponse struct {
	Resolved map[string]string `json:"resolved"`
	NotFound []string          `json:"not_found"`
}

func (r *ResolveAgentNamesResponse) GetResolved() map[string]string {
	if r == nil {
		return map[string]string{}
	}
	return r.Resolved
}

func (r *ResolveAgentNamesResponse) GetNotFound() []string {
	if r == nil {
		return []string{}
	}
	return r.NotFound
}
