// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// RoutersEvaluatorsEvaluatorResponseEvaluatorType - What the evaluator judges:
//
// - `tts`: TTS audio
// - `stt`: one transcript
// - `llm`: a reply with its conversation history
// - `llm-general`: a standalone input and output pair
// - `conversation`: a full conversation
type RoutersEvaluatorsEvaluatorResponseEvaluatorType string

const (
	RoutersEvaluatorsEvaluatorResponseEvaluatorTypeTts          RoutersEvaluatorsEvaluatorResponseEvaluatorType = "tts"
	RoutersEvaluatorsEvaluatorResponseEvaluatorTypeStt          RoutersEvaluatorsEvaluatorResponseEvaluatorType = "stt"
	RoutersEvaluatorsEvaluatorResponseEvaluatorTypeLlm          RoutersEvaluatorsEvaluatorResponseEvaluatorType = "llm"
	RoutersEvaluatorsEvaluatorResponseEvaluatorTypeLlmGeneral   RoutersEvaluatorsEvaluatorResponseEvaluatorType = "llm-general"
	RoutersEvaluatorsEvaluatorResponseEvaluatorTypeConversation RoutersEvaluatorsEvaluatorResponseEvaluatorType = "conversation"
)

func (e RoutersEvaluatorsEvaluatorResponseEvaluatorType) ToPointer() *RoutersEvaluatorsEvaluatorResponseEvaluatorType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RoutersEvaluatorsEvaluatorResponseEvaluatorType) IsExact() bool {
	if e != nil {
		switch *e {
		case "tts", "stt", "llm", "llm-general", "conversation":
			return true
		}
	}
	return false
}

// RoutersEvaluatorsEvaluatorResponseDataType - The modality the judge reads:
//
// - `text`
// - `audio`
type RoutersEvaluatorsEvaluatorResponseDataType string

const (
	RoutersEvaluatorsEvaluatorResponseDataTypeText  RoutersEvaluatorsEvaluatorResponseDataType = "text"
	RoutersEvaluatorsEvaluatorResponseDataTypeAudio RoutersEvaluatorsEvaluatorResponseDataType = "audio"
)

func (e RoutersEvaluatorsEvaluatorResponseDataType) ToPointer() *RoutersEvaluatorsEvaluatorResponseDataType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RoutersEvaluatorsEvaluatorResponseDataType) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "audio":
			return true
		}
	}
	return false
}

// RoutersEvaluatorsEvaluatorResponseOutputType - How the evaluator scores:
//
// - `binary`: pass or fail
// - `rating`: a numeric score, using the scale in `output_config`
type RoutersEvaluatorsEvaluatorResponseOutputType string

const (
	RoutersEvaluatorsEvaluatorResponseOutputTypeBinary RoutersEvaluatorsEvaluatorResponseOutputType = "binary"
	RoutersEvaluatorsEvaluatorResponseOutputTypeRating RoutersEvaluatorsEvaluatorResponseOutputType = "rating"
)

func (e RoutersEvaluatorsEvaluatorResponseOutputType) ToPointer() *RoutersEvaluatorsEvaluatorResponseOutputType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RoutersEvaluatorsEvaluatorResponseOutputType) IsExact() bool {
	if e != nil {
		switch *e {
		case "binary", "rating":
			return true
		}
	}
	return false
}

type RoutersEvaluatorsEvaluatorResponse struct {
	// Evaluator ID
	UUID string `json:"uuid"`
	// Evaluator name
	Name string `json:"name"`
	// What the evaluator checks
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// What the evaluator judges:
	//
	// - `tts`: TTS audio
	// - `stt`: one transcript
	// - `llm`: a reply with its conversation history
	// - `llm-general`: a standalone input and output pair
	// - `conversation`: a full conversation
	//
	EvaluatorType RoutersEvaluatorsEvaluatorResponseEvaluatorType `json:"evaluator_type"`
	// The modality the judge reads:
	//
	// - `text`
	// - `audio`
	//
	DataType RoutersEvaluatorsEvaluatorResponseDataType `json:"data_type"`
	// How the evaluator scores:
	//
	// - `binary`: pass or fail
	// - `rating`: a numeric score, using the scale in `output_config`
	//
	OutputType RoutersEvaluatorsEvaluatorResponseOutputType `json:"output_type"`
	// True when the evaluator is a built-in default or your workspace's editable copy of one. False for an evaluator you created yourself
	IsDefault bool `json:"is_default"`
	// Stable slug for a built-in default evaluator
	Slug optionalnullable.OptionalNullable[string] `json:"slug,omitzero"`
	// Stable slug of the built-in default this evaluator is your editable copy of. Set on your default forks so you can identify a specific default by it
	SourceDefaultSlug optionalnullable.OptionalNullable[string] `json:"source_default_slug,omitzero"`
	// ID of the version that is currently live
	LiveVersionID optionalnullable.OptionalNullable[string] `json:"live_version_id,omitzero"`
	// When the evaluator was created (ISO 8601 UTC)
	CreatedAt string `json:"created_at"`
	// When the evaluator was last updated (ISO 8601 UTC)
	UpdatedAt string `json:"updated_at"`
	// The version that is currently live
	LiveVersion optionalnullable.OptionalNullable[EvaluatorLiveVersionSummary] `json:"live_version,omitzero"`
}

func (r RoutersEvaluatorsEvaluatorResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RoutersEvaluatorsEvaluatorResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetUUID() string {
	if r == nil {
		return ""
	}
	return r.UUID
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetDescription() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetEvaluatorType() RoutersEvaluatorsEvaluatorResponseEvaluatorType {
	if r == nil {
		return RoutersEvaluatorsEvaluatorResponseEvaluatorType("")
	}
	return r.EvaluatorType
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetDataType() RoutersEvaluatorsEvaluatorResponseDataType {
	if r == nil {
		return RoutersEvaluatorsEvaluatorResponseDataType("")
	}
	return r.DataType
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetOutputType() RoutersEvaluatorsEvaluatorResponseOutputType {
	if r == nil {
		return RoutersEvaluatorsEvaluatorResponseOutputType("")
	}
	return r.OutputType
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetIsDefault() bool {
	if r == nil {
		return false
	}
	return r.IsDefault
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetSlug() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.Slug
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetSourceDefaultSlug() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.SourceDefaultSlug
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetLiveVersionID() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.LiveVersionID
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetUpdatedAt() string {
	if r == nil {
		return ""
	}
	return r.UpdatedAt
}

func (r *RoutersEvaluatorsEvaluatorResponse) GetLiveVersion() optionalnullable.OptionalNullable[EvaluatorLiveVersionSummary] {
	if r == nil {
		return nil
	}
	return r.LiveVersion
}
