// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// RoutersTestsTestResponseType - Test kind: `response`, `tool_call`, or `conversation`
type RoutersTestsTestResponseType string

const (
	RoutersTestsTestResponseTypeResponse     RoutersTestsTestResponseType = "response"
	RoutersTestsTestResponseTypeToolCall     RoutersTestsTestResponseType = "tool_call"
	RoutersTestsTestResponseTypeConversation RoutersTestsTestResponseType = "conversation"
)

func (e RoutersTestsTestResponseType) ToPointer() *RoutersTestsTestResponseType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RoutersTestsTestResponseType) IsExact() bool {
	if e != nil {
		switch *e {
		case "response", "tool_call", "conversation":
			return true
		}
	}
	return false
}

type RoutersTestsTestResponse struct {
	// Test ID
	UUID string `json:"uuid"`
	// Human-readable test name
	Name string `json:"name"`
	// Test kind: `response`, `tool_call`, or `conversation`
	Type RoutersTestsTestResponseType `json:"type"`
	// Calibrate test config (`history`, `evaluation`, optional `settings`)
	Config optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
	// Creation timestamp (ISO 8601 UTC)
	CreatedAt string `json:"created_at"`
	// Last-update timestamp (ISO 8601 UTC)
	UpdatedAt string `json:"updated_at"`
	// Linked evaluators, resolved to their current live version at read time
	Evaluators []map[string]any `json:"evaluators,omitzero"`
}

func (r RoutersTestsTestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RoutersTestsTestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RoutersTestsTestResponse) GetUUID() string {
	if r == nil {
		return ""
	}
	return r.UUID
}

func (r *RoutersTestsTestResponse) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RoutersTestsTestResponse) GetType() RoutersTestsTestResponseType {
	if r == nil {
		return RoutersTestsTestResponseType("")
	}
	return r.Type
}

func (r *RoutersTestsTestResponse) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if r == nil {
		return nil
	}
	return r.Config
}

func (r *RoutersTestsTestResponse) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RoutersTestsTestResponse) GetUpdatedAt() string {
	if r == nil {
		return ""
	}
	return r.UpdatedAt
}

func (r *RoutersTestsTestResponse) GetEvaluators() []map[string]any {
	if r == nil {
		return nil
	}
	return r.Evaluators
}
