// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RoutersAgentsEvaluatorLinkResponse struct {
	// Confirmation that the evaluators were linked
	Message string `json:"message"`
	// Evaluator IDs newly linked by this request
	Linked []string `json:"linked"`
	// Evaluator IDs skipped because they were already linked
	AlreadyLinked []string `json:"already_linked"`
}

func (r *RoutersAgentsEvaluatorLinkResponse) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RoutersAgentsEvaluatorLinkResponse) GetLinked() []string {
	if r == nil {
		return []string{}
	}
	return r.Linked
}

func (r *RoutersAgentsEvaluatorLinkResponse) GetAlreadyLinked() []string {
	if r == nil {
		return []string{}
	}
	return r.AlreadyLinked
}
