// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type Type string

const (
	TypeAgent      Type = "agent"
	TypeConnection Type = "connection"
)

func (e Type) ToPointer() *Type {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Type) IsExact() bool {
	if e != nil {
		switch *e {
		case "agent", "connection":
			return true
		}
	}
	return false
}

type RoutersAgentTestsAgentResponse struct {
	UUID      string                                            `json:"uuid"`
	Name      string                                            `json:"name"`
	Type      Type                                              `json:"type"`
	Config    optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
	CreatedAt string                                            `json:"created_at"`
	UpdatedAt string                                            `json:"updated_at"`
}

func (r RoutersAgentTestsAgentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RoutersAgentTestsAgentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RoutersAgentTestsAgentResponse) GetUUID() string {
	if r == nil {
		return ""
	}
	return r.UUID
}

func (r *RoutersAgentTestsAgentResponse) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RoutersAgentTestsAgentResponse) GetType() Type {
	if r == nil {
		return Type("")
	}
	return r.Type
}

func (r *RoutersAgentTestsAgentResponse) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if r == nil {
		return nil
	}
	return r.Config
}

func (r *RoutersAgentTestsAgentResponse) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RoutersAgentTestsAgentResponse) GetUpdatedAt() string {
	if r == nil {
		return ""
	}
	return r.UpdatedAt
}
