// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (s *Security) GetAPIKeyAuth() string {
	if s == nil {
		return ""
	}
	return s.APIKeyAuth
}
