// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// TaskType - Type of the task
type TaskType string

const (
	TaskTypeStt          TaskType = "stt"
	TaskTypeTts          TaskType = "tts"
	TaskTypeLlm          TaskType = "llm"
	TaskTypeLlmGeneral   TaskType = "llm-general"
	TaskTypeConversation TaskType = "conversation"
)

func (e TaskType) ToPointer() *TaskType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TaskType) IsExact() bool {
	if e != nil {
		switch *e {
		case "stt", "tts", "llm", "llm-general", "conversation":
			return true
		}
	}
	return false
}

type TaskSummaryResponse struct {
	// ID of the task
	TaskID string `json:"task_id"`
	// Type of the task
	TaskType TaskType `json:"task_type"`
	// The task's evaluators, stable across pages, each with its live rubric
	Evaluators []map[string]any `json:"evaluators"`
	// The annotators who labelled or commented on items in the task, stable across pages
	Annotators []map[string]any `json:"annotators"`
	// One row per item, evaluator, and version on this page, with the evaluator's value and each annotator's label
	Rows []map[string]any `json:"rows"`
	// Annotator comments, keyed by item ID
	ItemComments         map[string]any `json:"item_comments"`
	Pagination           PaginationMeta `json:"pagination"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (t TaskSummaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskSummaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskSummaryResponse) GetTaskID() string {
	if t == nil {
		return ""
	}
	return t.TaskID
}

func (t *TaskSummaryResponse) GetTaskType() TaskType {
	if t == nil {
		return TaskType("")
	}
	return t.TaskType
}

func (t *TaskSummaryResponse) GetEvaluators() []map[string]any {
	if t == nil {
		return []map[string]any{}
	}
	return t.Evaluators
}

func (t *TaskSummaryResponse) GetAnnotators() []map[string]any {
	if t == nil {
		return []map[string]any{}
	}
	return t.Annotators
}

func (t *TaskSummaryResponse) GetRows() []map[string]any {
	if t == nil {
		return []map[string]any{}
	}
	return t.Rows
}

func (t *TaskSummaryResponse) GetItemComments() map[string]any {
	if t == nil {
		return map[string]any{}
	}
	return t.ItemComments
}

func (t *TaskSummaryResponse) GetPagination() PaginationMeta {
	if t == nil {
		return PaginationMeta{}
	}
	return t.Pagination
}

func (t *TaskSummaryResponse) GetAdditionalProperties() map[string]any {
	if t == nil {
		return nil
	}
	return t.AdditionalProperties
}
