// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type TaskAgreementResponse struct {
	// ID of the task
	TaskID string `json:"task_id"`
	// Time bucket used for the trend series
	Bucket string `json:"bucket"`
	// Length of the trailing window in days
	Days       int64               `json:"days"`
	HumanHuman HumanAgreementBlock `json:"human_human"`
	// Agreement between each evaluator and the annotators, one entry per linked evaluator
	Evaluators           []map[string]any `json:"evaluators"`
	AdditionalProperties map[string]any   `additionalProperties:"true" json:"-"`
}

func (t TaskAgreementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskAgreementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskAgreementResponse) GetTaskID() string {
	if t == nil {
		return ""
	}
	return t.TaskID
}

func (t *TaskAgreementResponse) GetBucket() string {
	if t == nil {
		return ""
	}
	return t.Bucket
}

func (t *TaskAgreementResponse) GetDays() int64 {
	if t == nil {
		return 0
	}
	return t.Days
}

func (t *TaskAgreementResponse) GetHumanHuman() HumanAgreementBlock {
	if t == nil {
		return HumanAgreementBlock{}
	}
	return t.HumanHuman
}

func (t *TaskAgreementResponse) GetEvaluators() []map[string]any {
	if t == nil {
		return []map[string]any{}
	}
	return t.Evaluators
}

func (t *TaskAgreementResponse) GetAdditionalProperties() map[string]any {
	if t == nil {
		return nil
	}
	return t.AdditionalProperties
}
