// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// TestListResponseType - What the test judges:
//
// - `response`: judges the generated reply
// - `tool_call`: diffs the generated tool calls
// - `conversation`: judges the full conversation
type TestListResponseType string

const (
	TestListResponseTypeResponse     TestListResponseType = "response"
	TestListResponseTypeToolCall     TestListResponseType = "tool_call"
	TestListResponseTypeConversation TestListResponseType = "conversation"
)

func (e TestListResponseType) ToPointer() *TestListResponseType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TestListResponseType) IsExact() bool {
	if e != nil {
		switch *e {
		case "response", "tool_call", "conversation":
			return true
		}
	}
	return false
}

// TestListResponse - Trimmed test shape for list/index endpoints. The full config and hydrated
// evaluators live on the detail endpoint (`GET /tests/{uuid}`); the list keeps
// only what list and attach-dropdown views render.
type TestListResponse struct {
	// Unique ID for the test
	UUID string `json:"uuid"`
	// Name of the test
	Name string `json:"name"`
	// What the test judges:
	//
	// - `response`: judges the generated reply
	// - `tool_call`: diffs the generated tool calls
	// - `conversation`: judges the full conversation
	//
	Type TestListResponseType `json:"type"`
	// Trimmed config carrying only the test's description. Fetch the test by ID for the full config and evaluators
	Config optionalnullable.OptionalNullable[TestListConfig] `json:"config,omitzero"`
	// When the test was created (ISO 8601 UTC)
	CreatedAt string `json:"created_at"`
	// When the test was last updated (ISO 8601 UTC)
	UpdatedAt string `json:"updated_at"`
}

func (t TestListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestListResponse) GetUUID() string {
	if t == nil {
		return ""
	}
	return t.UUID
}

func (t *TestListResponse) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TestListResponse) GetType() TestListResponseType {
	if t == nil {
		return TestListResponseType("")
	}
	return t.Type
}

func (t *TestListResponse) GetConfig() optionalnullable.OptionalNullable[TestListConfig] {
	if t == nil {
		return nil
	}
	return t.Config
}

func (t *TestListResponse) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}

func (t *TestListResponse) GetUpdatedAt() string {
	if t == nil {
		return ""
	}
	return t.UpdatedAt
}
