// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TestCreateResponse struct {
	// ID of the newly created test
	UUID string `json:"uuid"`
	// Human-readable confirmation message
	Message string `json:"message"`
}

func (t *TestCreateResponse) GetUUID() string {
	if t == nil {
		return ""
	}
	return t.UUID
}

func (t *TestCreateResponse) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}
