// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
)

// TestRunCaseSummary - Flat summary for one test case in the run-LIST endpoints. Carries only
// enough to render a run's pass/fail breakdown and a case name. The full detail
// for each case (agent output, judge verdicts, reasoning, latency, cost, the
// test-case definition) lives on the run-DETAIL endpoint
// (`GET /agent-tests/run/{task_id}`).
type TestRunCaseSummary struct {
	// Name of the test case
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// Whether the case passed (null if it errored or is still running)
	Passed optionalnullable.OptionalNullable[bool] `json:"passed,omitzero"`
}

func (t *TestRunCaseSummary) GetName() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TestRunCaseSummary) GetPassed() optionalnullable.OptionalNullable[bool] {
	if t == nil {
		return nil
	}
	return t.Passed
}
