// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// TestCaseResult - Result for a single test case matching calibrate results.json structure
type TestCaseResult struct {
	TestCaseID   optionalnullable.OptionalNullable[string]         `json:"test_case_id,omitzero"`
	Name         optionalnullable.OptionalNullable[string]         `json:"name,omitzero"`
	Passed       optionalnullable.OptionalNullable[bool]           `json:"passed,omitzero"`
	Reasoning    optionalnullable.OptionalNullable[string]         `json:"reasoning,omitzero"`
	Output       optionalnullable.OptionalNullable[TestOutput]     `json:"output,omitzero"`
	TestCase     optionalnullable.OptionalNullable[map[string]any] `json:"test_case,omitzero"`
	JudgeResults optionalnullable.OptionalNullable[[]JudgeResult]  `json:"judge_results,omitzero"`
	LatencyMs    optionalnullable.OptionalNullable[float64]        `json:"latency_ms,omitzero"`
	Cost         optionalnullable.OptionalNullable[float64]        `json:"cost,omitzero"`
}

func (t TestCaseResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestCaseResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestCaseResult) GetTestCaseID() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.TestCaseID
}

func (t *TestCaseResult) GetName() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TestCaseResult) GetPassed() optionalnullable.OptionalNullable[bool] {
	if t == nil {
		return nil
	}
	return t.Passed
}

func (t *TestCaseResult) GetReasoning() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Reasoning
}

func (t *TestCaseResult) GetOutput() optionalnullable.OptionalNullable[TestOutput] {
	if t == nil {
		return nil
	}
	return t.Output
}

func (t *TestCaseResult) GetTestCase() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.TestCase
}

func (t *TestCaseResult) GetJudgeResults() optionalnullable.OptionalNullable[[]JudgeResult] {
	if t == nil {
		return nil
	}
	return t.JudgeResults
}

func (t *TestCaseResult) GetLatencyMs() optionalnullable.OptionalNullable[float64] {
	if t == nil {
		return nil
	}
	return t.LatencyMs
}

func (t *TestCaseResult) GetCost() optionalnullable.OptionalNullable[float64] {
	if t == nil {
		return nil
	}
	return t.Cost
}
