// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// TestCreateType - What the test judges:
//
// - `response`: judges the generated reply
// - `tool_call`: diffs the generated tool calls
// - `conversation`: judges the full conversation
type TestCreateType string

const (
	TestCreateTypeResponse     TestCreateType = "response"
	TestCreateTypeToolCall     TestCreateType = "tool_call"
	TestCreateTypeConversation TestCreateType = "conversation"
)

func (e TestCreateType) ToPointer() *TestCreateType {
	return &e
}
func (e *TestCreateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response":
		fallthrough
	case "tool_call":
		fallthrough
	case "conversation":
		*e = TestCreateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TestCreateType: %v", v)
	}
}

type TestCreate struct {
	// Name of the test, unique within the workspace
	Name string `json:"name"`
	// What the test judges:
	//
	// - `response`: judges the generated reply
	// - `tool_call`: diffs the generated tool calls
	// - `conversation`: judges the full conversation
	Type TestCreateType `json:"type"`
	// The calibrate test config. Three top-level keys.
	//
	// - `history` (array, required): the conversation up to the agent's turn. Each item is `{role, content}` with `role` one of `user`, `assistant`, `tool`. A `tool` message also carries `tool_call_id` and `name`.
	// - `evaluation` (object, required): `{type, ...}`, where `type` matches the test's `type` (below).
	// - `settings` (object, optional): e.g. `{"language": "en"}`.
	//
	// `evaluation` by test type:
	// - `response`: judge the agent's reply, graded by the linked evaluators. `{"type": "response"}`
	// - `conversation`: append the reply and judge the whole conversation. `{"type": "conversation"}`
	// - `tool_call`: diff the agent's tool calls against expected ones. Add `tool_calls`, a list of `{tool, arguments, accept_any_arguments?}`.
	//
	// For `tool_call`, each expected argument value is one of:
	// - `{"match_type": "exact", "value": <any>}`: must equal `value`
	// - `{"match_type": "llm_judge", "criteria": "..."}`: judged against the criteria
	// - `{"match_type": "any"}`: any value, only checks the argument was passed
	//
	// `response` / `conversation` example:
	// ```json
	// {
	//   "history": [{"role": "user", "content": "What is your return policy?"}],
	//   "evaluation": {"type": "response"},
	//   "settings": {"language": "en"}
	// }
	// ```
	//
	// `tool_call` example:
	// ```json
	// {
	//   "history": [{"role": "user", "content": "Book room 101 for tomorrow"}],
	//   "evaluation": {
	//     "type": "tool_call",
	//     "tool_calls": [
	//       {
	//         "tool": "book_room",
	//         "arguments": {
	//           "room": {"match_type": "exact", "value": "101"},
	//           "date": {"match_type": "llm_judge", "criteria": "tomorrow's date"}
	//         },
	//         "accept_any_arguments": false
	//       }
	//     ]
	//   }
	// }
	// ```
	//
	// Evaluators are linked via the separate `evaluators` field, not inside `config`.
	//
	// Omit to create the test with no config and fill it in later via update.
	Config optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
	// Evaluators to link. Used by `response` and `conversation` tests
	Evaluators optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] `json:"evaluators,omitzero"`
}

func (t TestCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestCreate) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TestCreate) GetType() TestCreateType {
	if t == nil {
		return TestCreateType("")
	}
	return t.Type
}

func (t *TestCreate) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.Config
}

func (t *TestCreate) GetEvaluators() optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] {
	if t == nil {
		return nil
	}
	return t.Evaluators
}
