// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type OutputType string

const (
	OutputTypeBinary OutputType = "binary"
	OutputTypeRating OutputType = "rating"
)

func (e OutputType) ToPointer() *OutputType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OutputType) IsExact() bool {
	if e != nil {
		switch *e {
		case "binary", "rating":
			return true
		}
	}
	return false
}

type TestRunEvaluator struct {
	// ID of the evaluator
	UUID optionalnullable.OptionalNullable[string] `json:"uuid,omitzero"`
	// Name of the evaluator
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// What the evaluator checks
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// Verdict shape: pass/fail or a numeric rating
	OutputType optionalnullable.OptionalNullable[OutputType] `json:"output_type,omitzero"`
	// Rubric: the scale values, labels, and colors a verdict maps to
	OutputConfig optionalnullable.OptionalNullable[map[string]any] `json:"output_config,omitzero"`
	// Lowest rating value. Set for rating evaluators
	ScaleMin optionalnullable.OptionalNullable[float64] `json:"scale_min,omitzero"`
	// Highest rating value. Set for rating evaluators
	ScaleMax optionalnullable.OptionalNullable[float64] `json:"scale_max,omitzero"`
	// Evaluator version this run used
	VersionNumber optionalnullable.OptionalNullable[int64] `json:"version_number,omitzero"`
}

func (t TestRunEvaluator) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestRunEvaluator) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestRunEvaluator) GetUUID() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.UUID
}

func (t *TestRunEvaluator) GetName() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TestRunEvaluator) GetDescription() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TestRunEvaluator) GetOutputType() optionalnullable.OptionalNullable[OutputType] {
	if t == nil {
		return nil
	}
	return t.OutputType
}

func (t *TestRunEvaluator) GetOutputConfig() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.OutputConfig
}

func (t *TestRunEvaluator) GetScaleMin() optionalnullable.OptionalNullable[float64] {
	if t == nil {
		return nil
	}
	return t.ScaleMin
}

func (t *TestRunEvaluator) GetScaleMax() optionalnullable.OptionalNullable[float64] {
	if t == nil {
		return nil
	}
	return t.ScaleMax
}

func (t *TestRunEvaluator) GetVersionNumber() optionalnullable.OptionalNullable[int64] {
	if t == nil {
		return nil
	}
	return t.VersionNumber
}
