// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// TestCreateType - Test kind (immutable after creation): `response` judges the generated reply, `tool_call` diffs generated tool calls, `conversation` judges the full conversation
type TestCreateType string

const (
	TestCreateTypeResponse     TestCreateType = "response"
	TestCreateTypeToolCall     TestCreateType = "tool_call"
	TestCreateTypeConversation TestCreateType = "conversation"
)

func (e TestCreateType) ToPointer() *TestCreateType {
	return &e
}
func (e *TestCreateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response":
		fallthrough
	case "tool_call":
		fallthrough
	case "conversation":
		*e = TestCreateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TestCreateType: %v", v)
	}
}

type TestCreate struct {
	// Human-readable test name, unique within the workspace
	Name string `json:"name"`
	// Test kind (immutable after creation): `response` judges the generated reply, `tool_call` diffs generated tool calls, `conversation` judges the full conversation
	Type TestCreateType `json:"type"`
	// Calibrate test config (`history`, `evaluation`, optional `settings`). Omit to create an empty shell to fill in later
	Config optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
	// Evaluators to link. **Required (>=1) for `type=conversation`** (no fallback judge). Omit for `response`/`tool_call` to link none
	Evaluators optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] `json:"evaluators,omitzero"`
}

func (t TestCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestCreate) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TestCreate) GetType() TestCreateType {
	if t == nil {
		return TestCreateType("")
	}
	return t.Type
}

func (t *TestCreate) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.Config
}

func (t *TestCreate) GetEvaluators() optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] {
	if t == nil {
		return nil
	}
	return t.Evaluators
}
