// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type TestRunStatusResponse struct {
	// Test run job ID
	TaskID string     `json:"task_id"`
	Status TaskStatus `json:"status"`
	// Total number of test cases
	TotalTests optionalnullable.OptionalNullable[int64] `json:"total_tests,omitzero"`
	// Number of test cases that passed
	Passed optionalnullable.OptionalNullable[int64] `json:"passed,omitzero"`
	// Number of test cases that failed
	Failed optionalnullable.OptionalNullable[int64] `json:"failed,omitzero"`
	// Aggregated response latency in milliseconds, as `{p50, p95, p99, count}`
	LatencyMs optionalnullable.OptionalNullable[map[string]any] `json:"latency_ms,omitzero"`
	// Aggregated cost as `{mean, min, max, count}` (USD)
	Cost optionalnullable.OptionalNullable[map[string]any] `json:"cost,omitzero"`
	// Aggregated token usage as `{mean, min, max, count}`
	TotalTokens optionalnullable.OptionalNullable[map[string]any] `json:"total_tokens,omitzero"`
	// The evaluators used in this run. Each verdict in `judge_results` links to one of these by `evaluator_uuid`
	Evaluators optionalnullable.OptionalNullable[[]TestRunEvaluator] `json:"evaluators,omitzero"`
	// Results for each test case
	Results optionalnullable.OptionalNullable[[]TestCaseResult] `json:"results,omitzero"`
	// True if the run failed
	Error *bool `default:"false" json:"error"`
	// Whether the run is shared publicly
	IsPublic *bool `default:"false" json:"is_public"`
	// Token for building the public share URL
	ShareToken optionalnullable.OptionalNullable[string] `json:"share_token,omitzero"`
}

func (t TestRunStatusResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestRunStatusResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestRunStatusResponse) GetTaskID() string {
	if t == nil {
		return ""
	}
	return t.TaskID
}

func (t *TestRunStatusResponse) GetStatus() TaskStatus {
	if t == nil {
		return TaskStatus("")
	}
	return t.Status
}

func (t *TestRunStatusResponse) GetTotalTests() optionalnullable.OptionalNullable[int64] {
	if t == nil {
		return nil
	}
	return t.TotalTests
}

func (t *TestRunStatusResponse) GetPassed() optionalnullable.OptionalNullable[int64] {
	if t == nil {
		return nil
	}
	return t.Passed
}

func (t *TestRunStatusResponse) GetFailed() optionalnullable.OptionalNullable[int64] {
	if t == nil {
		return nil
	}
	return t.Failed
}

func (t *TestRunStatusResponse) GetLatencyMs() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.LatencyMs
}

func (t *TestRunStatusResponse) GetCost() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.Cost
}

func (t *TestRunStatusResponse) GetTotalTokens() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.TotalTokens
}

func (t *TestRunStatusResponse) GetEvaluators() optionalnullable.OptionalNullable[[]TestRunEvaluator] {
	if t == nil {
		return nil
	}
	return t.Evaluators
}

func (t *TestRunStatusResponse) GetResults() optionalnullable.OptionalNullable[[]TestCaseResult] {
	if t == nil {
		return nil
	}
	return t.Results
}

func (t *TestRunStatusResponse) GetError() *bool {
	if t == nil {
		return nil
	}
	return t.Error
}

func (t *TestRunStatusResponse) GetIsPublic() *bool {
	if t == nil {
		return nil
	}
	return t.IsPublic
}

func (t *TestRunStatusResponse) GetShareToken() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.ShareToken
}
