// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

// TestResponseType - What the test judges:
//
// - `response`: judges the generated reply
// - `tool_call`: diffs the generated tool calls
// - `conversation`: judges the full conversation
type TestResponseType string

const (
	TestResponseTypeResponse     TestResponseType = "response"
	TestResponseTypeToolCall     TestResponseType = "tool_call"
	TestResponseTypeConversation TestResponseType = "conversation"
)

func (e TestResponseType) ToPointer() *TestResponseType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TestResponseType) IsExact() bool {
	if e != nil {
		switch *e {
		case "response", "tool_call", "conversation":
			return true
		}
	}
	return false
}

type TestResponse struct {
	// Unique ID for the test
	UUID string `json:"uuid"`
	// Name of the test
	Name string `json:"name"`
	// What the test judges:
	//
	// - `response`: judges the generated reply
	// - `tool_call`: diffs the generated tool calls
	// - `conversation`: judges the full conversation
	//
	Type TestResponseType `json:"type"`
	// The stored config: `history`, `evaluation`, and an optional `settings`
	Config optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
	// When the test was created (ISO 8601 UTC)
	CreatedAt string `json:"created_at"`
	// When the test was last updated (ISO 8601 UTC)
	UpdatedAt string `json:"updated_at"`
	// Linked evaluators, resolved to their current live version at read time
	Evaluators []map[string]any `json:"evaluators,omitzero"`
}

func (t TestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestResponse) GetUUID() string {
	if t == nil {
		return ""
	}
	return t.UUID
}

func (t *TestResponse) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TestResponse) GetType() TestResponseType {
	if t == nil {
		return TestResponseType("")
	}
	return t.Type
}

func (t *TestResponse) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.Config
}

func (t *TestResponse) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}

func (t *TestResponse) GetUpdatedAt() string {
	if t == nil {
		return ""
	}
	return t.UpdatedAt
}

func (t *TestResponse) GetEvaluators() []map[string]any {
	if t == nil {
		return nil
	}
	return t.Evaluators
}
