// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type TestUpdateType string

const (
	TestUpdateTypeResponse     TestUpdateType = "response"
	TestUpdateTypeToolCall     TestUpdateType = "tool_call"
	TestUpdateTypeConversation TestUpdateType = "conversation"
)

func (e TestUpdateType) ToPointer() *TestUpdateType {
	return &e
}
func (e *TestUpdateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response":
		fallthrough
	case "tool_call":
		fallthrough
	case "conversation":
		*e = TestUpdateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TestUpdateType: %v", v)
	}
}

type TestUpdate struct {
	// New test name. Omit to leave unchanged
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// Test type. Immutable — may only echo the existing value; a different value is rejected (400). Omit to leave unchanged
	Type optionalnullable.OptionalNullable[TestUpdateType] `json:"type,omitzero"`
	// Replacement calibrate config. Omit to leave unchanged
	Config optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
	// Replacement evaluator links (replaces the existing set). Omit to leave links unchanged; an empty list clears them (**rejected for `conversation` tests**)
	Evaluators optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] `json:"evaluators,omitzero"`
}

func (t TestUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestUpdate) GetName() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TestUpdate) GetType() optionalnullable.OptionalNullable[TestUpdateType] {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TestUpdate) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.Config
}

func (t *TestUpdate) GetEvaluators() optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] {
	if t == nil {
		return nil
	}
	return t.Evaluators
}
