// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type TestUpdateType string

const (
	TestUpdateTypeResponse     TestUpdateType = "response"
	TestUpdateTypeToolCall     TestUpdateType = "tool_call"
	TestUpdateTypeConversation TestUpdateType = "conversation"
)

func (e TestUpdateType) ToPointer() *TestUpdateType {
	return &e
}
func (e *TestUpdateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response":
		fallthrough
	case "tool_call":
		fallthrough
	case "conversation":
		*e = TestUpdateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TestUpdateType: %v", v)
	}
}

type TestUpdate struct {
	// New test name. Omit to leave unchanged
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// What the test judges:
	//
	// - `response`: judges the generated reply
	// - `tool_call`: diffs the generated tool calls
	// - `conversation`: judges the full conversation
	//
	// Immutable. Omit, or send the existing value. A different value is rejected (400).
	Type optionalnullable.OptionalNullable[TestUpdateType] `json:"type,omitzero"`
	// The calibrate test config. Three top-level keys.
	//
	// - `history` (array, required): the conversation up to the agent's turn. Each item is `{role, content}` with `role` one of `user`, `assistant`, `tool`. A `tool` message also carries `tool_call_id` and `name`.
	// - `evaluation` (object, required): `{type, ...}`, where `type` matches the test's `type` (below).
	// - `settings` (object, optional): e.g. `{"language": "en"}`.
	//
	// `evaluation` by test type:
	// - `response`: judge the agent's reply, graded by the linked evaluators. `{"type": "response"}`
	// - `conversation`: append the reply and judge the whole conversation. `{"type": "conversation"}`
	// - `tool_call`: diff the agent's tool calls against expected ones. Add `tool_calls`, a list of `{tool, arguments, accept_any_arguments?}`.
	//
	// For `tool_call`, each expected argument value is one of:
	// - `{"match_type": "exact", "value": <any>}`: must equal `value`
	// - `{"match_type": "llm_judge", "criteria": "..."}`: judged against the criteria
	// - `{"match_type": "any"}`: any value, only checks the argument was passed
	//
	// `response` / `conversation` example:
	// ```json
	// {
	//   "history": [{"role": "user", "content": "What is your return policy?"}],
	//   "evaluation": {"type": "response"},
	//   "settings": {"language": "en"}
	// }
	// ```
	//
	// `tool_call` example:
	// ```json
	// {
	//   "history": [{"role": "user", "content": "Book room 101 for tomorrow"}],
	//   "evaluation": {
	//     "type": "tool_call",
	//     "tool_calls": [
	//       {
	//         "tool": "book_room",
	//         "arguments": {
	//           "room": {"match_type": "exact", "value": "101"},
	//           "date": {"match_type": "llm_judge", "criteria": "tomorrow's date"}
	//         },
	//         "accept_any_arguments": false
	//       }
	//     ]
	//   }
	// }
	// ```
	//
	// Evaluators are linked via the separate `evaluators` field, not inside `config`.
	//
	// Replaces the stored config. Omit to leave unchanged.
	Config optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
	// New evaluator links for the test. Omit to leave unchanged. An empty list clears them, except on `conversation` tests, which must keep at least one
	Evaluators optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] `json:"evaluators,omitzero"`
}

func (t TestUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestUpdate) GetName() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TestUpdate) GetType() optionalnullable.OptionalNullable[TestUpdateType] {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TestUpdate) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.Config
}

func (t *TestUpdate) GetEvaluators() optionalnullable.OptionalNullable[[]RoutersTestsEvaluatorRef] {
	if t == nil {
		return nil
	}
	return t.Evaluators
}
