// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type TestCaseResult struct {
	// ID of the test case within the run
	TestCaseID optionalnullable.OptionalNullable[string] `json:"test_case_id,omitzero"`
	// Name of the test
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// Whether the case passed
	Passed optionalnullable.OptionalNullable[bool] `json:"passed,omitzero"`
	// The judge's reasoning, or the tool-call diff for a tool-call test
	Reasoning optionalnullable.OptionalNullable[string] `json:"reasoning,omitzero"`
	// The agent's output for this case
	Output optionalnullable.OptionalNullable[TestOutput] `json:"output,omitzero"`
	// The test case definition that was run
	TestCase optionalnullable.OptionalNullable[map[string]any] `json:"test_case,omitzero"`
	// One verdict for each evaluator
	JudgeResults optionalnullable.OptionalNullable[[]JudgeResult] `json:"judge_results,omitzero"`
	// How long the agent took to respond, in milliseconds
	LatencyMs optionalnullable.OptionalNullable[float64] `json:"latency_ms,omitzero"`
	// Cost of this case (USD)
	Cost optionalnullable.OptionalNullable[float64] `json:"cost,omitzero"`
}

func (t TestCaseResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestCaseResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestCaseResult) GetTestCaseID() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.TestCaseID
}

func (t *TestCaseResult) GetName() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TestCaseResult) GetPassed() optionalnullable.OptionalNullable[bool] {
	if t == nil {
		return nil
	}
	return t.Passed
}

func (t *TestCaseResult) GetReasoning() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Reasoning
}

func (t *TestCaseResult) GetOutput() optionalnullable.OptionalNullable[TestOutput] {
	if t == nil {
		return nil
	}
	return t.Output
}

func (t *TestCaseResult) GetTestCase() optionalnullable.OptionalNullable[map[string]any] {
	if t == nil {
		return nil
	}
	return t.TestCase
}

func (t *TestCaseResult) GetJudgeResults() optionalnullable.OptionalNullable[[]JudgeResult] {
	if t == nil {
		return nil
	}
	return t.JudgeResults
}

func (t *TestCaseResult) GetLatencyMs() optionalnullable.OptionalNullable[float64] {
	if t == nil {
		return nil
	}
	return t.LatencyMs
}

func (t *TestCaseResult) GetCost() optionalnullable.OptionalNullable[float64] {
	if t == nil {
		return nil
	}
	return t.Cost
}
