// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type TraceOutput struct {
	// The assistant reply text for this turn. Omit for turns that only issued tool calls
	Response optionalnullable.OptionalNullable[string] `json:"response,omitzero"`
	// Tool calls the agent issued for this turn. Omit for plain text replies
	ToolCalls optionalnullable.OptionalNullable[[]TraceToolCall] `json:"tool_calls,omitzero"`
}

func (t TraceOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TraceOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TraceOutput) GetResponse() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Response
}

func (t *TraceOutput) GetToolCalls() optionalnullable.OptionalNullable[[]TraceToolCall] {
	if t == nil {
		return nil
	}
	return t.ToolCalls
}
