// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
	"github.com/dalmia/calibrate-cli/internal/sdk/sdkinternal/utils"
)

type TraceIngest struct {
	// ID of the agent that produced the turn. Must be an agent in your workspace
	AgentID string `json:"agent_id"`
	// Your own ID for the last user message in `input`, stored for reference only. Omit if you have none
	MessageID optionalnullable.OptionalNullable[string] `json:"message_id,omitzero"`
	// Your own ID for the conversation this turn belongs to, stored for reference only. Omit if you have none
	ConversationID optionalnullable.OptionalNullable[string] `json:"conversation_id,omitzero"`
	// Conversation history up to the reported output, oldest turn first, in OpenAI chat format
	Input  []TraceTurn `json:"input"`
	Output TraceOutput `json:"output"`
	// Key-value pairs stored with the trace. Prefer OTel `gen_ai.*` key names where they fit. Omit if you have none
	Metadata optionalnullable.OptionalNullable[[]TraceMetadataEntry] `json:"metadata,omitzero"`
}

func (t TraceIngest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TraceIngest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TraceIngest) GetAgentID() string {
	if t == nil {
		return ""
	}
	return t.AgentID
}

func (t *TraceIngest) GetMessageID() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.MessageID
}

func (t *TraceIngest) GetConversationID() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.ConversationID
}

func (t *TraceIngest) GetInput() []TraceTurn {
	if t == nil {
		return []TraceTurn{}
	}
	return t.Input
}

func (t *TraceIngest) GetOutput() TraceOutput {
	if t == nil {
		return TraceOutput{}
	}
	return t.Output
}

func (t *TraceIngest) GetMetadata() optionalnullable.OptionalNullable[[]TraceMetadataEntry] {
	if t == nil {
		return nil
	}
	return t.Metadata
}
