// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
)

type TraceIngestResponse struct {
	// Unique ID for the trace
	UUID string `json:"uuid"`
	// The message ID you sent, if any
	MessageID optionalnullable.OptionalNullable[string] `json:"message_id,omitzero"`
	// The conversation ID you sent, if any
	ConversationID optionalnullable.OptionalNullable[string] `json:"conversation_id,omitzero"`
	// When the trace was created (ISO 8601 UTC)
	CreatedAt string `json:"created_at"`
}

func (t *TraceIngestResponse) GetUUID() string {
	if t == nil {
		return ""
	}
	return t.UUID
}

func (t *TraceIngestResponse) GetMessageID() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.MessageID
}

func (t *TraceIngestResponse) GetConversationID() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.ConversationID
}

func (t *TraceIngestResponse) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}
