// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dalmia/calibrate-cli/internal/sdk/optionalnullable"
)

type VariableSpec struct {
	// Name of a `{{placeholder}}` used in the system prompt
	Name string `json:"name"`
	// What the variable is for. Omit if self-evident
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// Default value used when you omit this variable. Omit for no default
	Default optionalnullable.OptionalNullable[string] `json:"default,omitzero"`
}

func (v *VariableSpec) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *VariableSpec) GetDescription() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *VariableSpec) GetDefault() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Default
}
