// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VersionCreateResponse struct {
	// ID of the newly created version
	VersionUUID string `json:"version_uuid"`
	// The version's number. The first version is 1, and it goes up by one for each new version of the evaluator
	VersionNumber int64 `json:"version_number"`
}

func (v *VersionCreateResponse) GetVersionUUID() string {
	if v == nil {
		return ""
	}
	return v.VersionUUID
}

func (v *VersionCreateResponse) GetVersionNumber() int64 {
	if v == nil {
		return 0
	}
	return v.VersionNumber
}
