// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package annotationtasks

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createEvaluatorRunCmdMeta = []flagutil.FlagMeta{
	{FlagName: "task-uuid", Shorthand: "t", FieldPath: "TaskUUID", Kind: flagutil.FlagKindString, Required: true, Description: "Annotation task to act on [required]"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "evaluators", Shorthand: "e", FieldPath: "Body.Evaluators", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"evaluators"`, Description: "The evaluators to run. Each must be linked to the task [required]"},
	{FlagName: "item-ids", Shorthand: "i", FieldPath: "Body.ItemIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Item IDs to run on. **Required when `select_all=false`**. Ignored when `select_all=true`"},
	{FlagName: "select-all", Shorthand: "s", FieldPath: "Body.SelectAll", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "When `true`, run on every item in the task. Set `q` to run only items whose name matches it"},
	{FlagName: "q", FieldPath: "Body.Q", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"q,omitempty"`, Description: "Case-insensitive substring filter on `payload.name`. Applies only when `select_all=true`"},
}

// initCreateEvaluatorRunCmd initializes the create-evaluator-run command.
func initCreateEvaluatorRunCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-evaluator-run",
		Short:   "Run evaluators on items",
		Long:    "Run evaluators on task items as a background job",
		Example: "  calibrate annotation-tasks create-evaluator-run --task-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479 --evaluators '[]'",
		RunE:    runCreateEvaluatorRunCmd,
		Aliases: []string{"cer"},
	}
	flagutil.RegisterFlags(cmd, createEvaluatorRunCmdMeta)
	if err := flagutil.ValidateMeta[operations.StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostRequest](createEvaluatorRunCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-evaluator-run: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateEvaluatorRunCmd executes the create-evaluator-run command.
func runCreateEvaluatorRunCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createEvaluatorRunCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createEvaluatorRunCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StartEvaluatorRunAnnotationTasksTaskUUIDEvaluatorRunsPostRequest](cmd, createEvaluatorRunCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AnnotationTasks.CreateEvaluatorRun(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
