// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package annotationtasks

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createLabellingJobsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "task-uuid", Shorthand: "t", FieldPath: "TaskUUID", Kind: flagutil.FlagKindString, Required: true, Description: "Annotation task to act on [required]"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "annotator-ids", Shorthand: "a", FieldPath: "Body.AnnotatorIds", Kind: flagutil.FlagKindStringArray, Required: true, Description: "Annotator IDs to assign, creating one labelling job for each annotator. Must be in your workspace [required]"},
	{FlagName: "item-ids", Shorthand: "i", FieldPath: "Body.ItemIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Item IDs to assign. **Required when `select_all=false`**. Ignored when `select_all=true`"},
	{FlagName: "select-all", Shorthand: "s", FieldPath: "Body.SelectAll", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "When `true`, assign every item in the task and ignore `item_ids`. Set `q` to assign only items whose name matches it"},
	{FlagName: "q", FieldPath: "Body.Q", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"q,omitempty"`, Description: "Case-insensitive substring filter on `payload.name`. Applies only when `select_all=true`"},
	{FlagName: "evaluator-ids", Shorthand: "e", FieldPath: "Body.EvaluatorIds", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"evaluator_ids,omitempty"`, Description: "Subset of the task's linked evaluators to show in these jobs. Must be a subset of the current links, an empty list gives a 400. Applies to every annotator's job. Omit (`None`) to snapshot every linked evaluator"},
}

// initCreateLabellingJobsCmd initializes the create-labelling-jobs command.
func initCreateLabellingJobsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-labelling-jobs",
		Short:   "Create labelling jobs",
		Long:    "Assign items to annotators, creating one labelling job per annotator",
		Example: "  calibrate annotation-tasks create-labelling-jobs --task-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479 --annotator-ids '[\"f47ac10b-58cc-4372-a567-0e02b2c3d479\"]'",
		RunE:    runCreateLabellingJobsCmd,
		Aliases: []string{"clj"},
	}
	flagutil.RegisterFlags(cmd, createLabellingJobsCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateJobsAnnotationTasksTaskUUIDJobsPostRequest](createLabellingJobsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-labelling-jobs: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateLabellingJobsCmd executes the create-labelling-jobs command.
func runCreateLabellingJobsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createLabellingJobsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createLabellingJobsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateJobsAnnotationTasksTaskUUIDJobsPostRequest](cmd, createLabellingJobsCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AnnotationTasks.CreateLabellingJobs(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
