// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package annotationtasks

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var linkEvaluatorCmdMeta = []flagutil.FlagMeta{
	{FlagName: "task-uuid", Shorthand: "t", FieldPath: "TaskUUID", Kind: flagutil.FlagKindString, Required: true, Description: "Annotation task to act on [required]"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "evaluator-id", Shorthand: "e", FieldPath: "Body.EvaluatorID", Kind: flagutil.FlagKindString, Required: true, Description: "The evaluator to link. Must be one you created or a built-in default [required]"},
}

// initLinkEvaluatorCmd initializes the link-evaluator command.
func initLinkEvaluatorCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "link-evaluator",
		Short:   "Link evaluator to task",
		Long:    "Link an evaluator to a task, appending it to the display order",
		Example: "  calibrate annotation-tasks link-evaluator --task-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479 --evaluator-id f47ac10b-58cc-4372-a567-0e02b2c3d479",
		RunE:    runLinkEvaluatorCmd,
		Aliases: []string{"le"},
	}
	flagutil.RegisterFlags(cmd, linkEvaluatorCmdMeta)
	if err := flagutil.ValidateMeta[operations.LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostRequest](linkEvaluatorCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for link-evaluator: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runLinkEvaluatorCmd executes the link-evaluator command.
func runLinkEvaluatorCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, linkEvaluatorCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, linkEvaluatorCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.LinkEvaluatorToTaskAnnotationTasksTaskUUIDEvaluatorsPostRequest](cmd, linkEvaluatorCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AnnotationTasks.LinkEvaluator(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
