// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package annotationtasks

import (
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitAnnotationTasksRoot(parent *cobra.Command) error {
	var AnnotationTasksCmd = &cobra.Command{
		Use:   "annotation-tasks",
		Short: "Operations for annotation-tasks",
		Long:  "Operations for annotation-tasks",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"ata"},
	}

	if err := initCreateCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	if err := initListCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	if err := initGetCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	if err := initSetEvaluatorsCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	if err := initAddItemsCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	if err := initUpdateItemsCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	if err := initCreateEvaluatorRunCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	if err := initGetEvaluatorRunCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	if err := initGetAgreementCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	if err := initGetSummaryCmd(AnnotationTasksCmd); err != nil {
		return err
	}

	parent.AddCommand(AnnotationTasksCmd)
	return nil
}
