// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package annotationtasks

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var setEvaluatorsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "task-uuid", Shorthand: "t", FieldPath: "TaskUUID", Kind: flagutil.FlagKindString, Required: true, Description: "Annotation task to act on [required]"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "evaluator-ids", Shorthand: "e", FieldPath: "Body.EvaluatorIds", Kind: flagutil.FlagKindStringArray, Required: true, Description: "The full ordered set of evaluators the task should end up linked to, in display order. Missing ones are unlinked, new ones are linked, and the order sets their position. Send an empty list to unlink all. Each must be one you created or a built-in default [required]"},
}

// initSetEvaluatorsCmd initializes the set-evaluators command.
func initSetEvaluatorsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "set-evaluators",
		Short:   "Update task evaluators",
		Long:    "Replace a task's linked evaluators with the given ordered set, linking, unlinking, and reordering as needed",
		Example: "  calibrate annotation-tasks set-evaluators --task-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479 --evaluator-ids '[\"f47ac10b-58cc-4372-a567-0e02b2c3d479\"]'",
		RunE:    runSetEvaluatorsCmd,
		Aliases: []string{"se"},
	}
	flagutil.RegisterFlags(cmd, setEvaluatorsCmdMeta)
	if err := flagutil.ValidateMeta[operations.SetTaskEvaluatorsAnnotationTasksTaskUUIDEvaluatorsPutRequest](setEvaluatorsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for set-evaluators: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runSetEvaluatorsCmd executes the set-evaluators command.
func runSetEvaluatorsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, setEvaluatorsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, setEvaluatorsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.SetTaskEvaluatorsAnnotationTasksTaskUUIDEvaluatorsPutRequest](cmd, setEvaluatorsCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AnnotationTasks.SetEvaluators(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
