// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package annotationtasks

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateItemsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "task-uuid", Shorthand: "t", FieldPath: "TaskUUID", Kind: flagutil.FlagKindString, Required: true, Description: "Annotation task to act on [required]"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "updates", Shorthand: "u", FieldPath: "Body.Updates", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"updates"`, Description: "The new payload for each item you're updating. Entries not in this task, or referencing deleted items, are skipped [required]"},
}

// initUpdateItemsCmd initializes the update-items command.
func initUpdateItemsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update-items",
		Short:   "Bulk update items",
		Long:    "Bulk-update item payloads in a task",
		Example: "  calibrate annotation-tasks update-items --task-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479 --updates '[{\"uuid\":\"f47ac10b-58cc-4372-a567-0e02b2c3d479\",\"payload\":\"<value>\"}]'",
		RunE:    runUpdateItemsCmd,
		Aliases: []string{"ui"},
	}
	flagutil.RegisterFlags(cmd, updateItemsCmdMeta)
	if err := flagutil.ValidateMeta[operations.BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutRequest](updateItemsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update-items: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateItemsCmd executes the update-items command.
func runUpdateItemsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateItemsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateItemsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.BulkUpdateItemsAnnotationTasksTaskUUIDItemsPutRequest](cmd, updateItemsCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AnnotationTasks.UpdateItems(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
