// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agents

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var linkEvaluatorsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "agent-uuid", Shorthand: "a", FieldPath: "AgentUUID", Kind: flagutil.FlagKindString, Required: true, Description: "The agent to link the evaluators to [required]"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "evaluator-ids", Shorthand: "e", FieldPath: "Body.EvaluatorIds", Kind: flagutil.FlagKindStringArray, Required: true, Description: "The evaluators to link to the agent. Ones that are already linked are skipped. Each must be one you created or a built-in default [required]"},
}

// initLinkEvaluatorsCmd initializes the link-evaluators command.
func initLinkEvaluatorsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "link-evaluators",
		Short:   "Link evaluators to agent",
		Long:    "Link one or more existing evaluators to an agent, skipping any already linked",
		Example: "  calibrate agents link-evaluators --agent-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479 --evaluator-ids '[\"f47ac10b-58cc-4372-a567-0e02b2c3d479\"]'",
		RunE:    runLinkEvaluatorsCmd,
		Aliases: []string{"le"},
	}
	flagutil.RegisterFlags(cmd, linkEvaluatorsCmdMeta)
	if err := flagutil.ValidateMeta[operations.LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostRequest](linkEvaluatorsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for link-evaluators: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runLinkEvaluatorsCmd executes the link-evaluators command.
func runLinkEvaluatorsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, linkEvaluatorsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, linkEvaluatorsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.LinkEvaluatorsToAgentAgentsAgentUUIDEvaluatorsPostRequest](cmd, linkEvaluatorsCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Agents.LinkEvaluators(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
