// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agents

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listCmdMeta = []flagutil.FlagMeta{
	{FlagName: "q", FieldPath: "Q", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=q"`, Description: "Case-insensitive substring search on `name`. Blank is a no-op"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=limit"`, Description: "Maximum number of items to return. Omit for no limit (all items)"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "Number of items to skip before returning results"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
}

// initListCmd initializes the list command.
func initListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List agents",
		Long:    "Get the list of all your agents",
		Example: "  calibrate agents list",
		RunE:    runListCmd,
	}
	flagutil.RegisterFlags(cmd, listCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListAgentsAgentsGetRequest](listCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListCmd executes the list command.
func runListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListAgentsAgentsGetRequest](cmd, listCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Agents.List(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
