// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agents

import (
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitAgentsRoot(parent *cobra.Command) error {
	var AgentsCmd = &cobra.Command{
		Use:   "agents",
		Short: "Operations for agents",
		Long:  "Operations for agents",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initVerifyConnectionCmd(AgentsCmd); err != nil {
		return err
	}

	if err := initResolveCmd(AgentsCmd); err != nil {
		return err
	}

	if err := initCreateCmd(AgentsCmd); err != nil {
		return err
	}

	if err := initListCmd(AgentsCmd); err != nil {
		return err
	}

	if err := initGetCmd(AgentsCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(AgentsCmd); err != nil {
		return err
	}

	if err := initListEvaluatorsCmd(AgentsCmd); err != nil {
		return err
	}

	if err := initLinkEvaluatorsCmd(AgentsCmd); err != nil {
		return err
	}

	parent.AddCommand(AgentsCmd)
	return nil
}
