// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agents

import (
	"fmt"
	"github.com/dalmia/calibrate-cli/internal/client"
	"github.com/dalmia/calibrate-cli/internal/flagutil"
	"github.com/dalmia/calibrate-cli/internal/interactive"
	"github.com/dalmia/calibrate-cli/internal/output"
	"github.com/dalmia/calibrate-cli/internal/sdk"
	"github.com/dalmia/calibrate-cli/internal/sdk/models/operations"
	"github.com/dalmia/calibrate-cli/internal/usage"
	"github.com/spf13/cobra"
)

var verifyConnectionCmdMeta = []flagutil.FlagMeta{
	{FlagName: "agent-uuid", Shorthand: "a", FieldPath: "AgentUUID", Kind: flagutil.FlagKindString, Required: true, Description: "The agent whose connection to verify [required]"},
	{FlagName: "x-api-key", Shorthand: "x", FieldPath: "XAPIKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `header:"style=simple,explode=false,name=X-API-Key"`, Description: "string value"},
	{FlagName: "model", FieldPath: "Body.Model", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"model,omitempty"`, Description: "Model to verify. Omit for a basic connection check. Provide it for a model-specific check before benchmarking that model"},
	{FlagName: "messages", FieldPath: "Body.Messages", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"messages,omitempty"`, Description: "Sample chat messages to send during verification. Omit to use the default probe"},
}

// initVerifyConnectionCmd initializes the verify-connection command.
func initVerifyConnectionCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "verify-connection",
		Short:   "Verify agent connection",
		Long:    "Verify an agent's connection and persist the result when successful",
		Example: "  calibrate agents verify-connection --agent-uuid f47ac10b-58cc-4372-a567-0e02b2c3d479",
		RunE:    runVerifyConnectionCmd,
		Aliases: []string{"vc"},
	}
	flagutil.RegisterFlags(cmd, verifyConnectionCmdMeta)
	if err := flagutil.ValidateMeta[operations.VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostRequest](verifyConnectionCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for verify-connection: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runVerifyConnectionCmd executes the verify-connection command.
func runVerifyConnectionCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, verifyConnectionCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, verifyConnectionCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.VerifyAgentConnectionAgentsAgentUUIDVerifyConnectionPostRequest](cmd, verifyConnectionCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Agents.VerifyConnection(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
